// ===== PRICING CONTROL HUB V3 - APP =====
document.addEventListener('DOMContentLoaded',()=>{init()});
function init(){setDate();setupNav();setupModal();renderView('dashboard')}
function setDate(){document.getElementById('headerDate').textContent=new Date().toLocaleDateString('es-CR',{weekday:'long',year:'numeric',month:'long',day:'numeric'})}
function setupNav(){document.querySelectorAll('.nav-item').forEach(i=>{i.addEventListener('click',e=>{e.preventDefault();document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));i.classList.add('active');renderView(i.dataset.view)})});document.getElementById('menuToggle').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'))}
function setupModal(){document.getElementById('modalClose').addEventListener('click',closeModal);document.getElementById('modalOverlay').addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal()})}
function openModal(t,b,f=''){document.getElementById('modalTitle').textContent=t;document.getElementById('modalBody').innerHTML=b;document.getElementById('modalFooter').innerHTML=f;document.getElementById('modalOverlay').classList.add('active')}
function closeModal(){document.getElementById('modalOverlay').classList.remove('active')}
function toast(msg,type='success'){const c=document.getElementById('toastContainer');const t=document.createElement('div');t.className='toast '+type;t.textContent=msg;c.appendChild(t);setTimeout(()=>t.remove(),4000)}
function renderView(v){const titles={dashboard:'Dashboard Ejecutivo',productos:'Maestro de Productos',calcNuevo:'Cálculo Precio - Código Nuevo',calcUsado:'Cálculo Precio - Usado con Código Nuevo',cambioCosto:'Cambio de Costo y Precio Propuesto',homologacion:'Homologación de Precios por Lado',competencia:'Monitoreo de Competencia',investigacion:'Investigación de Mercado',ajustes:'Ajustes de Precio',aprobaciones:'Aprobaciones',integracion:'Integración API Punto de Venta',historial:'Histórico y Tendencia del Producto',reglas:'Reglas y Parámetros',lago:'Arquitectura / Lago de Datos'};
document.getElementById('headerTitle').textContent=titles[v]||'';const c=document.getElementById('contentArea');
switch(v){case'dashboard':c.innerHTML=vDashboard();break;case'productos':c.innerHTML=vProductos();break;case'calcNuevo':c.innerHTML=vCalcNuevo();break;case'calcUsado':c.innerHTML=vCalcUsado();break;case'cambioCosto':c.innerHTML=vCambioCosto();break;case'homologacion':c.innerHTML=vHomologacion();break;case'competencia':c.innerHTML=vCompetencia();break;case'investigacion':c.innerHTML=vInvestigacion();break;case'ajustes':c.innerHTML=vAjustes();break;case'aprobaciones':c.innerHTML=vAprobaciones();break;case'integracion':c.innerHTML=vIntegracion();break;case'historial':c.innerHTML=vHistorial();break;case'reglas':c.innerHTML=vReglas();break;case'lago':c.innerHTML=vLago();break}}

// ===== DASHBOARD =====
function vDashboard(){
const t=productos.length,pNew=productos.filter(p=>p.tipoIngreso==='Código nuevo'&&p.condicion==='Nuevo').length,pUsed=productos.filter(p=>p.condicion==='Usado'&&p.tipoIngreso==='Código nuevo').length,cc=productos.filter(p=>p.estado.includes('Cambio costo')).length,auto=solicitudesAjuste.filter(s=>s.estado==='Aplicado').length,pend=solicitudesAjuste.filter(s=>s.estado==='Pendiente de aprobación').length,sobre=productos.filter(p=>p.alerta==='Sobreprecio').length,bajo=productos.filter(p=>p.alerta==='Precio bajo').length,lados=productos.filter(p=>p.tieneLado&&p.precio>0).length/2,newCode=productos.filter(p=>p.alerta==='Nuevo código').length,errAPI=integPOS.errores,envPOS=integPOS.aplicados;
return`<div class="kpi-grid">
${kpi('📦',t,'Productos','blue')}${kpi('🆕',pNew,'Nuevos Pend.','cyan')}${kpi('♻️',pUsed,'Usados Pend.','purple')}${kpi('📈',cc,'Cambios Costo','yellow')}${kpi('⚡',auto,'Autos Aplicados','green')}${kpi('⏳',pend,'Pend. Aprob.','yellow')}${kpi('🔴',sobre,'Sobreprecio','red')}${kpi('🟡',bajo,'Precio Bajo','yellow')}${kpi('↔️',Math.floor(lados),'Homologados','blue')}${kpi('🆕',newCode,'Nuevo Código','red')}${kpi('❌',errAPI,'Errores API','red')}${kpi('✅',envPOS,'Enviados POS','green')}
</div>
<div class="summary-grid">
<div class="card"><div class="card-header"><h3>🚨 Alertas Inteligentes</h3></div><div class="card-body"><div class="table-wrap"><table><thead><tr><th>SKU</th><th>Tipo</th><th>Descripción</th><th>Severidad</th><th>Acción</th></tr></thead><tbody>
${alertasInteligentes.map(a=>`<tr><td><strong>${a.sku}</strong></td><td>${a.tipo}</td><td style="max-width:220px">${a.desc}</td><td><span class="badge ${badge(a.severidad)}">${a.severidad}</span></td><td><span class="badge badge-primary">${a.accion}</span></td></tr>`).join('')}
</tbody></table></div></div></div>
<div class="card"><div class="card-header"><h3>📊 Estado de Pricing</h3></div><div class="card-body">
${['Activo','Sobreprecio','Precio bajo','Pendiente precio','Cambio costo','Liquidación','Margen bajo'].map(e=>{const c=productos.filter(p=>p.estado===e||p.estado.includes(e)).length;const w=(c/t*100).toFixed(0);return c?`<div class="mb-1" style="font-size:11px"><span>${e}: ${c}</span><div class="progress-bar"><div class="progress-fill" style="width:${w}%;background:${e.includes('Sobre')||e.includes('Margen')?'#dc2626':e.includes('bajo')||e.includes('costo')?'#d97706':'#059669'}"></div></div></div>`:''}).join('')}
</div></div></div>`;
}
function kpi(icon,val,label,color){return`<div class="kpi-card ${color}"><div class="kpi-icon">${icon}</div><div class="kpi-value">${val}</div><div class="kpi-label">${label}</div></div>`}

// ===== MAESTRO PRODUCTOS =====
function vProductos(){return`<div class="filters-bar">
<input class="form-control" id="fSku" placeholder="SKU / Desc" onkeyup="filtProd()"><select class="form-control" id="fMarca" onchange="filtProd()"><option value="">Marca</option>${MARCAS.map(m=>`<option>${m}</option>`).join('')}</select><select class="form-control" id="fCond" onchange="filtProd()"><option value="">Condición</option><option>Nuevo</option><option>Usado</option></select><select class="form-control" id="fEst" onchange="filtProd()"><option value="">Estado</option><option>Activo</option><option>Sobreprecio</option><option>Precio bajo</option><option>Pendiente precio</option><option>Cambio costo</option><option>Liquidación</option><option>Margen bajo</option><option>Lado incompleto</option></select><select class="form-control" id="fLado" onchange="filtProd()"><option value="">Lado</option><option value="si">Con lado</option><option value="no">Sin lado</option></select><button class="btn btn-secondary" onclick="csvProd()">📥 CSV</button></div>
<div class="card"><div class="card-body"><div class="table-wrap"><table><thead><tr><th>SKU</th><th>Descripción</th><th>Marca</th><th>Cond.</th><th>Ingreso</th><th>Costo</th><th>Precio</th><th>Markup</th><th>Inv.</th><th>Lado</th><th>Estado</th><th>POS</th><th>Acciones</th></tr></thead><tbody id="tProd">${rowsProd(productos)}</tbody></table></div></div></div>`}
function rowsProd(ps){return ps.map(p=>`<tr><td><strong>${p.sku}</strong></td><td style="max-width:180px">${p.desc}</td><td>${p.marca}</td><td><span class="badge ${badge(p.condicion)}">${p.condicion}</span></td><td><span class="badge ${p.tipoIngreso==='Código nuevo'?'badge-info':'badge-secondary'}">${p.tipoIngreso}</span></td><td>${fmt(p.costo)}</td><td>${fmt(p.precio)}</td><td>${calcMarkup(p.precio,p.costo)}%</td><td>${p.inventario}</td><td>${p.tieneLado?p.lado:'-'}</td><td><span class="badge ${badge(p.estado)}">${p.estado}</span></td><td><span class="badge ${badge(p.posEstado)}">${p.posEstado.substring(0,8)}</span></td><td><div class="btn-group"><button class="btn btn-sm btn-outline" onclick="detProd(${p.id})">👁️</button><button class="btn btn-sm btn-primary" onclick="crearAjuste(${p.id})">💰</button></div></td></tr>`).join('')}
function filtProd(){const s=document.getElementById('fSku').value.toLowerCase(),m=document.getElementById('fMarca').value,c=document.getElementById('fCond').value,e=document.getElementById('fEst').value,l=document.getElementById('fLado').value;let f=productos.filter(p=>{if(s&&!p.sku.toLowerCase().includes(s)&&!p.desc.toLowerCase().includes(s))return false;if(m&&p.marca!==m)return false;if(c&&p.condicion!==c)return false;if(e&&!p.estado.includes(e))return false;if(l==='si'&&!p.tieneLado)return false;if(l==='no'&&p.tieneLado)return false;return true});document.getElementById('tProd').innerHTML=rowsProd(f)}
function detProd(id){const p=productos.find(x=>x.id===id);if(!p)return;openModal(p.sku,`<div class="product-summary">
${[['SKU',p.sku],['Descripción',p.desc],['Marca',p.marca],['Familia',p.familia],['Categoría',p.categoria],['Copro',p.copro],['Condición',p.condicion],['Ingreso',p.tipoIngreso],['Origen',p.origen],['Calidad',p.rangoCalidad],['Proveedor',p.provActual],['Prov. Anterior',p.provAnterior||'N/A'],['Costo',fmt(p.costo)],['Precio',fmt(p.precio)],['Markup',calcMarkup(p.precio,p.costo)+'%'],['Margen',calcMargen(p.precio,p.costo)+'%'],['Inventario',p.inventario],['Rotación',p.rotacion],['Lado',p.tieneLado?p.lado+' → '+p.skuPareja:'No'],['Última Eval.',p.ultimaEval||'Nunca'],['Estado',p.estado],['POS',p.posEstado]].map(([l,v])=>`<div class="product-summary-item"><label>${l}</label><span>${v}</span></div>`).join('')}
</div>`)}
function csvProd(){let c='SKU,Descripción,Marca,Condición,Costo,Precio,Markup,Estado\n';productos.forEach(p=>{c+=`${p.sku},"${p.desc}",${p.marca},${p.condicion},${p.costo},${p.precio},${calcMarkup(p.precio,p.costo)}%,${p.estado}\n`});dl(c,'maestro_productos.csv')}
function dl(csv,name){const b=new Blob([csv],{type:'text/csv;charset=utf-8;'});const l=document.createElement('a');l.href=URL.createObjectURL(b);l.download=name;l.click();toast('CSV exportado')}

// ===== CÁLCULO PRECIO CÓDIGO NUEVO =====
function vCalcNuevo(){const pn=productos.filter(p=>p.tipoIngreso==='Código nuevo'&&p.condicion==='Nuevo');return`<div class="card"><div class="card-header"><h3>Calcular Precio - Producto Nuevo con Código Nuevo</h3></div><div class="card-body">
<p class="text-muted mb-2">Producto con código nuevo = SKU que no existe en el inventario. Todo producto con código nuevo requiere aprobación antes de envío al POS.</p>
<div class="form-row"><div class="form-group"><label>SKU</label><input class="form-control" id="cn_sku" placeholder="LG-XXX-000"></div><div class="form-group"><label>Descripción</label><input class="form-control" id="cn_desc"></div><div class="form-group"><label>Marca</label><select class="form-control" id="cn_marca">${MARCAS.map(m=>`<option>${m}</option>`).join('')}</select></div></div>
<div class="form-row"><div class="form-group"><label>Familia</label><select class="form-control" id="cn_fam">${FAMILIAS.map(f=>`<option>${f}</option>`).join('')}</select></div><div class="form-group"><label>Categoría</label><select class="form-control" id="cn_cat">${CATEGORIAS.map(c=>`<option>${c}</option>`).join('')}</select></div><div class="form-group"><label>Copro</label><input class="form-control" id="cn_copro"></div></div>
<div class="form-row"><div class="form-group"><label>Origen</label><select class="form-control" id="cn_origen">${ORIGENES.map(o=>`<option>${o}</option>`).join('')}</select></div><div class="form-group"><label>Calidad</label><select class="form-control" id="cn_cal"><option>Premium</option><option>Medio</option><option>Entrada</option></select></div><div class="form-group"><label>Rotación Esperada</label><select class="form-control" id="cn_rot"><option>Alta</option><option>Media</option><option>Baja</option></select></div></div>
<div class="form-row"><div class="form-group"><label>Costo</label><input type="number" class="form-control" id="cn_costo" placeholder="0"></div><div class="form-group"><label>Inventario Inicial</label><input type="number" class="form-control" id="cn_inv" value="10"></div><div class="form-group"><label>Proveedor</label><input class="form-control" id="cn_prov"></div></div>
<div class="form-row"><div class="form-group"><label>Precio Competencia (si existe)</label><input type="number" class="form-control" id="cn_comp" placeholder="0"></div><div class="form-group"><label>Disponibilidad Origen</label><select class="form-control" id="cn_disp"><option>Alta</option><option>Media</option><option>Baja</option></select></div><div class="form-group"><label>Antigüedad</label><input class="form-control" id="cn_antig" placeholder="2015-2020"></div></div>
<div class="form-group"><label>Observación</label><textarea class="form-control" id="cn_obs"></textarea></div>
<div class="btn-group mt-2"><button class="btn btn-primary btn-lg" onclick="calcPrecioNuevo()">🧮 Calcular Precio</button></div>
<div id="cn_resultado"></div></div></div>
${pn.length?`<div class="card mt-2"><div class="card-header"><h3>Productos Nuevos Pendientes de Precio</h3></div><div class="card-body"><div class="table-wrap"><table><thead><tr><th>SKU</th><th>Descripción</th><th>Marca</th><th>Costo</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${pn.map(p=>`<tr><td>${p.sku}</td><td>${p.desc}</td><td>${p.marca}</td><td>${fmt(p.costo)}</td><td><span class="badge badge-info">Pendiente</span></td><td><button class="btn btn-sm btn-primary" onclick="autoCalcNuevo(${p.id})">Calcular</button></td></tr>`).join('')}</tbody></table></div></div></div>`:''}`}
function calcPrecioNuevo(){
const costo=parseInt(document.getElementById('cn_costo').value)||0;if(!costo){toast('Ingrese costo','error');return}
const cal=document.getElementById('cn_cal').value,rot=document.getElementById('cn_rot').value,origen=document.getElementById('cn_origen').value,comp=parseInt(document.getElementById('cn_comp').value)||0,disp=document.getElementById('cn_disp').value;
const result=motorPrecioNuevo(costo,cal,rot,origen,comp,disp);
document.getElementById('cn_resultado').innerHTML=`<div class="card mt-2" style="border:2px solid var(--primary)"><div class="card-body">
<h4 class="mb-2">💰 Resultado del Cálculo</h4>
<div class="form-row"><div class="form-group"><label>Precio Sugerido</label><span class="kpi-value" style="font-size:20px">${fmt(result.precio)}</span></div><div class="form-group"><label>Markup</label><span class="fw-bold">${result.markup}%</span></div><div class="form-group"><label>Margen</label><span class="fw-bold">${result.margen}%</span></div></div>
<div class="ia-box"><h4>🤖 Explicación IA</h4><p>${result.explicacion}</p></div>
<p class="mt-2"><span class="badge badge-warning">⚠️ Requiere aprobación</span> Todo producto con código nuevo debe ser aprobado.</p>
<div class="btn-group mt-2"><button class="btn btn-success" onclick="enviarAprobNuevo()">📤 Enviar a Aprobación</button><button class="btn btn-secondary" onclick="toast('Borrador guardado')">💾 Guardar Borrador</button></div>
</div></div>`}
function motorPrecioNuevo(costo,cal,rot,origen,comp,disp){
let factorCal={'Premium':2.2,'Medio':1.8,'Entrada':1.5}[cal]||1.8;
let factorRot={'Alta':0.9,'Media':1.0,'Baja':1.15}[rot]||1.0;
let factorOrigen=origen==='Importado'?1.05:1.0;
let factorDisp={'Alta':0.95,'Media':1.0,'Baja':1.1}[disp]||1.0;
let precioBase=Math.round(costo*factorCal*factorRot*factorOrigen*factorDisp);
if(comp>0){precioBase=Math.round((precioBase*0.6)+(comp*0.4))}
const markup=calcMarkup(precioBase,costo);const margen=calcMargen(precioBase,costo);
const explicacion=`Precio calculado con ponderación: Calidad ${cal} (x${factorCal}), Rotación ${rot} (x${factorRot}), Origen ${origen} (x${factorOrigen.toFixed(2)}), Disponibilidad ${disp} (x${factorDisp}). ${comp?`Precio competencia ₡${comp.toLocaleString()} integrado con peso 40%.`:''} Markup resultante: ${markup}%, Margen: ${margen}%.`;
return{precio:precioBase,markup,margen,explicacion}}
function autoCalcNuevo(id){const p=productos.find(x=>x.id===id);if(!p)return;const r=motorPrecioNuevo(p.costo,p.rangoCalidad==='Premium'?'Premium':p.rangoCalidad==='Medio'?'Medio':'Entrada',p.rotacion,p.origen,0,p.rangoCalidad==='Premium'?'Baja':'Media');openModal(`Precio Sugerido: ${p.sku}`,`<div class="product-summary"><div class="product-summary-item"><label>Producto</label><span>${p.desc}</span></div><div class="product-summary-item"><label>Costo</label><span>${fmt(p.costo)}</span></div><div class="product-summary-item"><label>Precio Sugerido</label><span class="fw-bold">${fmt(r.precio)}</span></div><div class="product-summary-item"><label>Markup</label><span>${r.markup}%</span></div><div class="product-summary-item"><label>Margen</label><span>${r.margen}%</span></div></div><div class="ia-box"><h4>🤖 Explicación IA</h4><p>${r.explicacion}</p></div>`,`<button class="btn btn-success" onclick="aplicarPrecioNuevo(${id},${r.precio})">Enviar a Aprobación</button><button class="btn btn-secondary" onclick="closeModal()">Cancelar</button>`)}
function aplicarPrecioNuevo(id,precio){const p=productos.find(x=>x.id===id);p.precio=precio;p.estado='Pendiente precio';const sol={id:solicitudesAjuste.length+1,numero:genNumSol(),productoId:id,sku:p.sku,desc:p.desc,precioActual:0,costo:p.costo,markupActual:0,precioSugerido:precio,nuevoPrecio:precio,motivo:'Cambio de costo',accionSugerida:'Asignar precio',justificacion:'Producto código nuevo',estado:'Pendiente de aprobación',solicitante:'Carlos Mora',fecha:new Date().toISOString().split('T')[0],requiereAprobacion:true,regla:'Código nuevo requiere aprobación',posEstado:'Pendiente de envío'};solicitudesAjuste.push(sol);closeModal();toast(`${p.sku}: Precio ${fmt(precio)} enviado a aprobación`);renderView('calcNuevo')}
function enviarAprobNuevo(){toast('Solicitud enviada a aprobación');document.getElementById('cn_resultado').innerHTML='<p class="text-success mt-2">✅ Solicitud creada exitosamente</p>'}

// ===== CÁLCULO PRECIO USADO =====
function vCalcUsado(){const pu=productos.filter(p=>p.condicion==='Usado'&&p.tipoIngreso==='Código nuevo');return`<div class="card"><div class="card-header"><h3>Calcular Precio - Producto Usado con Código Nuevo</h3></div><div class="card-body">
<p class="text-muted mb-2">Producto usado que ingresa con SKU nuevo. La letra "U" identifica usados. El precio no necesariamente es igual al nuevo equivalente.</p>
<div class="form-row"><div class="form-group"><label>Código Usado</label><input class="form-control" id="cu_sku" placeholder="LG-XXX-000U"></div><div class="form-group"><label>Descripción</label><input class="form-control" id="cu_desc"></div><div class="form-group"><label>Marca</label><select class="form-control" id="cu_marca">${MARCAS.map(m=>`<option>${m}</option>`).join('')}</select></div></div>
<div class="form-row"><div class="form-group"><label>Calidad Usado</label><select class="form-control" id="cu_cal"><option>Usado A</option><option>Usado B</option><option>Usado C</option></select></div><div class="form-group"><label>Estado Físico</label><select class="form-control"><option>Bueno</option><option>Regular</option><option>Reparado</option></select></div><div class="form-group"><label>Disponibilidad Origen</label><select class="form-control" id="cu_disp"><option>Alta</option><option>Media</option><option>Baja</option></select></div></div>
<div class="form-row"><div class="form-group"><label>Costo</label><input type="number" class="form-control" id="cu_costo" placeholder="0"></div><div class="form-group"><label>Precio Nuevo Equivalente</label><input type="number" class="form-control" id="cu_eqNuevo" placeholder="0"></div><div class="form-group"><label>Precio Competencia Usado</label><input type="number" class="form-control" id="cu_comp" placeholder="0"></div></div>
<div class="form-group"><label>Observación</label><textarea class="form-control" id="cu_obs"></textarea></div>
<button class="btn btn-primary btn-lg" onclick="calcPrecioUsado()">🧮 Calcular Precio Usado</button>
<div id="cu_resultado"></div></div></div>
${pu.length?`<div class="card mt-2"><div class="card-header"><h3>Usados Pendientes de Precio</h3></div><div class="card-body"><div class="table-wrap"><table><thead><tr><th>SKU</th><th>Descripción</th><th>Calidad</th><th>Costo</th><th>Acción</th></tr></thead><tbody>${pu.map(p=>`<tr><td>${p.sku}</td><td>${p.desc}</td><td><span class="badge badge-purple">${p.rangoCalidad}</span></td><td>${fmt(p.costo)}</td><td><button class="btn btn-sm btn-primary" onclick="autoCalcUsado(${p.id})">Calcular</button></td></tr>`).join('')}</tbody></table></div></div></div>`:''}`}
function calcPrecioUsado(){
const costo=parseInt(document.getElementById('cu_costo').value)||0;if(!costo){toast('Ingrese costo','error');return}
const cal=document.getElementById('cu_cal').value,disp=document.getElementById('cu_disp').value,eqNuevo=parseInt(document.getElementById('cu_eqNuevo').value)||0,comp=parseInt(document.getElementById('cu_comp').value)||0;
const r=motorPrecioUsado(costo,cal,disp,eqNuevo,comp);
document.getElementById('cu_resultado').innerHTML=`<div class="card mt-2" style="border:2px solid var(--purple)"><div class="card-body">
<h4 class="mb-2">♻️ Resultado Precio Usado</h4>
<div class="form-row"><div class="form-group"><label>Precio Sugerido</label><span class="kpi-value" style="font-size:20px">${fmt(r.precio)}</span></div><div class="form-group"><label>Markup</label><span class="fw-bold">${r.markup}%</span></div><div class="form-group"><label>Margen</label><span class="fw-bold">${r.margen}%</span></div>${eqNuevo?`<div class="form-group"><label>Dif. vs Nuevo</label><span class="text-success">${r.diffNuevo}%</span></div>`:''}</div>
<div class="ia-box"><h4>🤖 Explicación IA</h4><p>${r.explicacion}</p></div>
${r.alerta?`<p class="text-warning mt-1">⚠️ ${r.alerta}</p>`:''}
<p class="mt-2"><span class="badge badge-warning">Requiere aprobación</span></p>
<div class="btn-group mt-2"><button class="btn btn-success" onclick="toast('Enviado a aprobación')">📤 Enviar a Aprobación</button></div>
</div></div>`}
function motorPrecioUsado(costo,cal,disp,eqNuevo,comp){
let factorCal={'Usado A':1.6,'Usado B':1.35,'Usado C':1.15}[cal]||1.35;
let factorDisp={'Alta':0.9,'Media':1.0,'Baja':1.15}[disp]||1.0;
let precio=Math.round(costo*factorCal*factorDisp);
if(eqNuevo>0){const maxUsado=Math.round(eqNuevo*0.7);if(precio>maxUsado)precio=maxUsado}
if(comp>0){precio=Math.round((precio*0.5)+(comp*0.5))}
const markup=calcMarkup(precio,costo);const margen=calcMargen(precio,costo);
const diffNuevo=eqNuevo?calcDiff(precio,eqNuevo):'N/A';
let alerta=null;if(!eqNuevo&&!comp)alerta='Sin equivalencia nueva ni precio competencia. Requiere revisión manual.';
const explicacion=`Precio usado calculado: Calidad ${cal} (x${factorCal}), Disponibilidad ${disp} (x${factorDisp}). ${eqNuevo?`Tope 70% del nuevo equiv. (${fmt(eqNuevo)}).`:'Sin equivalente nuevo.'} ${comp?`Competencia usado: ${fmt(comp)} (peso 50%).`:'Sin referencia competencia usada.'} Markup: ${markup}%.`;
return{precio,markup,margen,diffNuevo,explicacion,alerta}}
function autoCalcUsado(id){const p=productos.find(x=>x.id===id);const r=motorPrecioUsado(p.costo,p.rangoCalidad,p.rotacion==='Baja'?'Baja':'Media',0,0);openModal(`Precio Usado: ${p.sku}`,`<div class="product-summary"><div class="product-summary-item"><label>Producto</label><span>${p.desc}</span></div><div class="product-summary-item"><label>Calidad</label><span>${p.rangoCalidad}</span></div><div class="product-summary-item"><label>Costo</label><span>${fmt(p.costo)}</span></div><div class="product-summary-item"><label>Precio Sugerido</label><span class="fw-bold">${fmt(r.precio)}</span></div><div class="product-summary-item"><label>Markup</label><span>${r.markup}%</span></div></div><div class="ia-box"><h4>🤖 IA</h4><p>${r.explicacion}</p></div>${r.alerta?`<p class="text-warning mt-1">⚠️ ${r.alerta}</p>`:''}`,`<button class="btn btn-success" onclick="aplicarPrecioNuevo(${id},${r.precio})">Enviar a Aprobación</button><button class="btn btn-secondary" onclick="closeModal()">Cancelar</button>`)}

// ===== CAMBIO DE COSTO =====
function vCambioCosto(){const cc=productos.filter(p=>p.estado.includes('Cambio costo')||p.provActual!==p.provAnterior&&p.provAnterior);return`<div class="card"><div class="card-header"><h3>Detección y Evaluación de Cambios de Costo</h3><button class="btn btn-primary" onclick="detectarCambios()">🔍 Detectar Cambios</button></div><div class="card-body">
<p class="text-muted mb-2">Reglas: <5% no cambiar | 5-10% revisar | >10% ajustar auto si cumple | >40% + proveedor diferente → nuevo código | Neteo excluido | Markup 17%-1000%</p>
<div class="table-wrap"><table><thead><tr><th>SKU</th><th>Producto</th><th>Prov. Actual</th><th>Prov. Ant.</th><th>Costo Ant.</th><th>Nuevo Costo</th><th>Var. %</th><th>Precio Act.</th><th>Precio Prop.</th><th>Markup Prop.</th><th>Estado</th><th>Acción</th><th>Aprob.</th></tr></thead><tbody id="tCC">
${renderCC(cc)}</tbody></table></div></div></div>`}
function renderCC(prods){return prods.map(p=>{const costoAnt=p.provAnterior&&p.provAnterior!==p.provActual?Math.round(p.costo*0.65):Math.round(p.costo*0.92);const varCosto=parseFloat(calcDiff(p.costo,costoAnt));const absVar=Math.abs(varCosto);let accion,estado,req=false;
if(absVar<5){accion='No cambiar';estado='En rango'}else if(absVar<=10){accion='Revisar';estado='Revisar';req=false}else{accion='Ajustar auto';estado='Ajustar';req=false}
if(absVar>40&&p.provActual!==p.provAnterior&&p.provAnterior){accion='Crear nuevo código';estado='Fuera rango';req=true}
const markup=parseFloat(calcMarkup(p.precio,p.costo));if(markup<17||markup>1000){accion='Excluir (markup fuera rango)';estado='Excluir'}
const precioProp=Math.round(p.costo*(1+markup/100));
return`<tr><td><strong>${p.sku}</strong></td><td style="max-width:150px">${p.desc}</td><td>${p.provActual}</td><td>${p.provAnterior||'-'}</td><td>${fmt(costoAnt)}</td><td>${fmt(p.costo)}</td><td class="${varCosto>0?'text-danger':'text-success'}">${varCosto>0?'+':''}${varCosto.toFixed(1)}%</td><td>${fmt(p.precio)}</td><td><strong>${fmt(precioProp)}</strong></td><td>${calcMarkup(precioProp,p.costo)}%</td><td><span class="badge ${badge(estado)}">${estado}</span></td><td><span class="badge badge-primary">${accion}</span></td><td>${req?'<span class="badge badge-warning">Sí</span>':'<span class="badge badge-success">No</span>'}</td></tr>`}).join('')}
function detectarCambios(){toast('Análisis ejecutado: '+productos.filter(p=>p.estado.includes('Cambio')).length+' cambios detectados')}

// ===== HOMOLOGACIÓN POR LADO =====
function vHomologacion(){const parejas=[];productos.filter(p=>p.tieneLado&&p.lado==='Derecho').forEach(pd=>{const pi=productos.find(x=>x.sku===pd.skuPareja);parejas.push({der:pd,izq:pi||null})});
return`<div class="card"><div class="card-header"><h3>Homologación de Precios por Lado</h3><button class="btn btn-primary" onclick="toast('Parejas buscadas: ${parejas.length}')">🔍 Buscar Parejas</button></div><div class="card-body">
<p class="text-muted mb-2">Regla: Productos izquierdo/derecho deben tener mismo precio. Precio Homologado = Promedio de precios sugeridos.</p>
<div class="table-wrap"><table><thead><tr><th>SKU Der.</th><th>Costo Der.</th><th>Precio Sug. Der.</th><th>SKU Izq.</th><th>Costo Izq.</th><th>Precio Sug. Izq.</th><th>Precio Homologado</th><th>Margen Der.</th><th>Margen Izq.</th><th>Estado</th><th>Acción</th></tr></thead><tbody>
${parejas.map(({der:d,izq:i})=>{if(!i)return`<tr><td>${d.sku}</td><td>${fmt(d.costo)}</td><td>${fmt(d.precio)}</td><td colspan="4"><span class="badge badge-warning">⚠️ Sin pareja</span></td><td>-</td><td>-</td><td><span class="badge badge-warning">Incompleto</span></td><td>Buscar pareja</td></tr>`;
const pSugD=d.precio||Math.round(d.costo*1.8);const pSugI=i.precio||Math.round(i.costo*1.8);const homol=Math.round((pSugD+pSugI)/2);const mD=calcMargen(homol,d.costo);const mI=calcMargen(homol,i.costo);const ok=parseFloat(mD)>=reglas.margenMin&&parseFloat(mI)>=reglas.margenMin;
return`<tr><td><strong>${d.sku}</strong></td><td>${fmt(d.costo)}</td><td>${fmt(pSugD)}</td><td><strong>${i.sku}</strong></td><td>${fmt(i.costo)}</td><td>${fmt(pSugI)}</td><td class="fw-bold">${fmt(homol)}</td><td>${mD}%</td><td>${mI}%</td><td><span class="badge ${ok?'badge-success':'badge-warning'}">${ok?'OK':'Revisar margen'}</span></td><td><button class="btn btn-sm btn-success" onclick="aplicarHomol(${d.id},${i.id},${homol})">Aplicar</button></td></tr>`}).join('')}
</tbody></table></div></div></div>`}
function aplicarHomol(idD,idI,precio){const d=productos.find(x=>x.id===idD);const i=productos.find(x=>x.id===idI);if(d)d.precio=precio;if(i)i.precio=precio;toast(`Precio homologado ${fmt(precio)} aplicado a ambos lados`);renderView('homologacion')}

// ===== COMPETENCIA =====
function vCompetencia(){return`<div class="card"><div class="card-header"><h3>Monitoreo de Competencia</h3><button class="btn btn-primary" onclick="buscarComp()">🔍 Buscar Precios</button></div><div class="card-body">
<div class="filters-bar"><input class="form-control" id="fcBuscar" placeholder="Buscar..."><select class="form-control" id="fcComp"><option value="">Competidor</option>${COMPETIDORES.map(c=>`<option>${c}</option>`).join('')}</select><select class="form-control" id="fcEst"><option value="">Estado</option><option>Sobreprecio</option><option>Precio bajo</option><option>En rango</option></select><button class="btn btn-secondary" onclick="filtComp()">Filtrar</button></div>
<div class="table-wrap"><table><thead><tr><th>SKU</th><th>Cond.</th><th>Precio LG</th><th>Competidor</th><th>Precio Comp.</th><th>Prom. Merc.</th><th>Min</th><th>Max</th><th>Dif. %</th><th>Confianza</th><th>Estado</th><th>Precio Obj.</th><th>Sugerencia</th><th>Acción</th></tr></thead><tbody id="tComp">${renderComp(preciosCompetencia)}</tbody></table></div></div></div>`}
function renderComp(data){return data.map(pc=>{const p=productos.find(x=>x.id===pc.productoId);if(!p)return'';const diff=parseFloat(calcDiff(p.precio,pc.promMercado));let estado='En rango',sugerencia='Mantener',precioObj=p.precio;
if(diff>reglas.sobreprecio){estado='Sobreprecio';precioObj=Math.round(pc.promMercado*(1+reglas.permitidoSobreMercado/100));sugerencia=`Reducir ${fmt(p.precio-precioObj)}`}
else if(diff<-reglas.precioBajo){estado='Precio bajo';sugerencia='Oportunidad aumento';precioObj=p.precio}
if(pc.confianza<80)estado='Revisión manual';
return`<tr><td><strong>${p.sku}</strong></td><td><span class="badge ${badge(p.condicion)}">${p.condicion}</span></td><td>${fmt(p.precio)}</td><td>${pc.competidor}</td><td>${fmt(pc.precio)}</td><td>${fmt(pc.promMercado)}</td><td>${fmt(pc.minMercado)}</td><td>${fmt(pc.maxMercado)}</td><td class="${diff>0?'text-danger':'text-success'}">${diff>0?'+':''}${diff.toFixed(1)}%</td><td>${pc.confianza}%</td><td><span class="badge ${estado==='Sobreprecio'?'badge-danger':estado==='Precio bajo'?'badge-warning':'badge-success'}">${estado}</span></td><td>${fmt(precioObj)}</td><td>${sugerencia}</td><td><button class="btn btn-sm btn-outline" onclick="crearAjuste(${p.id})">💰</button></td></tr>`}).join('')}
function filtComp(){const b=document.getElementById('fcBuscar').value.toLowerCase(),c=document.getElementById('fcComp').value,e=document.getElementById('fcEst').value;let f=preciosCompetencia.filter(pc=>{const p=productos.find(x=>x.id===pc.productoId);if(!p)return false;if(b&&!p.sku.toLowerCase().includes(b)&&!p.desc.toLowerCase().includes(b))return false;if(c&&pc.competidor!==c)return false;if(e){const diff=parseFloat(calcDiff(p.precio,pc.promMercado));if(e==='Sobreprecio'&&diff<=reglas.sobreprecio)return false;if(e==='Precio bajo'&&diff>=-reglas.precioBajo)return false;if(e==='En rango'&&(diff>reglas.sobreprecio||diff<-reglas.precioBajo))return false}return true});document.getElementById('tComp').innerHTML=renderComp(f)}
function buscarComp(){document.getElementById('tComp').innerHTML='<tr><td colspan="14" class="text-center">🔄 Buscando...</td></tr>';setTimeout(()=>{preciosCompetencia.push({id:preciosCompetencia.length+1,productoId:5,competidor:'Uno Partes',prodComp:'Alternador Vitara',precio:132000,promMercado:135000,minMercado:128000,maxMercado:142000,confianza:84,condicion:'Nuevo',fecha:new Date().toISOString().split('T')[0],fuente:'Web'});document.getElementById('tComp').innerHTML=renderComp(preciosCompetencia);toast('3 coincidencias nuevas')},1500)}

// ===== INVESTIGACIÓN MERCADO =====
function vInvestigacion(){return`<div class="card"><div class="card-header"><h3>Registrar Precio Competencia</h3><div class="btn-group"><button class="btn btn-secondary" onclick="openModal('Carga CSV','<p>Seleccione archivo CSV.</p><input type=file class=form-control>','<button class=btn-primary onclick=closeModal();toast(\"8 registros cargados\")>Procesar</button>')">📂 CSV</button><button class="btn btn-outline" onclick="limpInv()">🧹</button></div></div><div class="card-body">
<div class="form-row"><div class="form-group"><label>Producto La Guaca</label><select class="form-control" id="iv_prod"><option value="">Seleccionar...</option>${productos.map(p=>`<option value="${p.id}">${p.sku} - ${p.desc}</option>`).join('')}</select></div><div class="form-group"><label>Competidor</label><select class="form-control" id="iv_comp"><option value="">Seleccionar...</option>${COMPETIDORES.map(c=>`<option>${c}</option>`).join('')}</select></div><div class="form-group"><label>Condición</label><select class="form-control" id="iv_cond"><option>Nuevo</option><option>Usado</option><option>No identificado</option></select></div></div>
<div class="form-row"><div class="form-group"><label>Producto Competencia</label><input class="form-control" id="iv_prodC"></div><div class="form-group"><label>Marca</label><input class="form-control" id="iv_marca"></div><div class="form-group"><label>OEM</label><input class="form-control" id="iv_oem"></div></div>
<div class="form-row"><div class="form-group"><label>Precio</label><input type="number" class="form-control" id="iv_precio"></div><div class="form-group"><label>Fuente</label><select class="form-control" id="iv_fuente">${FUENTES.map(f=>`<option>${f}</option>`).join('')}</select></div><div class="form-group"><label>Fecha</label><input type="date" class="form-control" id="iv_fecha" value="${new Date().toISOString().split('T')[0]}"></div></div>
<div class="form-row"><div class="form-group"><label>Link</label><input class="form-control" id="iv_link"></div><div class="form-group"><label>Evidencia</label><input type="file" class="form-control"></div><div class="form-group"><label>Usuario</label><input class="form-control" id="iv_user" value="Carlos Mora"></div></div>
<div class="form-group"><label>Observaciones</label><textarea class="form-control" id="iv_obs"></textarea></div>
<button class="btn btn-primary btn-lg" onclick="guardarInv()">💾 Guardar</button></div></div>
<div class="card mt-2"><div class="card-header"><h3>Registros</h3></div><div class="card-body"><div class="table-wrap"><table><thead><tr><th>SKU</th><th>Competidor</th><th>Cond.</th><th>Precio</th><th>Fuente</th><th>Fecha</th><th>Validación</th><th>Acciones</th></tr></thead><tbody id="tInv">${renderInv()}</tbody></table></div></div></div>`}
function renderInv(){return registrosInvestigacion.map(r=>`<tr><td>${r.sku}</td><td>${r.competidor}</td><td>${r.condicion}</td><td>${fmt(r.precio)}</td><td>${r.fuente}</td><td>${r.fecha}</td><td><span class="badge ${badge(r.validacion)}">${r.validacion}</span></td><td><div class="btn-group">${r.validacion==='Pendiente'?`<button class="btn btn-sm btn-success" onclick="valInv(${r.id})">✅</button><button class="btn btn-sm btn-danger" onclick="rejInv(${r.id})">❌</button>`:''}</div></td></tr>`).join('')}
function guardarInv(){const pid=parseInt(document.getElementById('iv_prod').value),comp=document.getElementById('iv_comp').value,precio=parseInt(document.getElementById('iv_precio').value);if(!pid||!comp||!precio){toast('Complete campos','error');return}const p=productos.find(x=>x.id===pid);registrosInvestigacion.push({id:registrosInvestigacion.length+1,productoId:pid,sku:p.sku,competidor:comp,prodComp:document.getElementById('iv_prodC').value,marca:document.getElementById('iv_marca').value,modelo:'',oem:document.getElementById('iv_oem').value,categoria:'',condicion:document.getElementById('iv_cond').value,precio,moneda:'CRC',fecha:document.getElementById('iv_fecha').value,fuente:document.getElementById('iv_fuente').value,link:document.getElementById('iv_link').value,evidencia:'',obs:document.getElementById('iv_obs').value,validacion:'Pendiente',usuario:document.getElementById('iv_user').value});
preciosCompetencia.push({id:preciosCompetencia.length+1,productoId:pid,competidor:comp,prodComp:document.getElementById('iv_prodC').value,precio,promMercado:precio,minMercado:precio,maxMercado:precio,confianza:95,condicion:document.getElementById('iv_cond').value,fecha:document.getElementById('iv_fecha').value,fuente:document.getElementById('iv_fuente').value});
document.getElementById('tInv').innerHTML=renderInv();toast('Precio registrado');limpInv()}
function valInv(id){const r=registrosInvestigacion.find(x=>x.id===id);if(r)r.validacion='Validado';document.getElementById('tInv').innerHTML=renderInv();toast('Validado')}
function rejInv(id){const r=registrosInvestigacion.find(x=>x.id===id);if(r)r.validacion='Rechazado';document.getElementById('tInv').innerHTML=renderInv();toast('Rechazado','warning')}
function limpInv(){['iv_prod','iv_comp','iv_prodC','iv_marca','iv_oem','iv_precio','iv_link','iv_obs'].forEach(x=>{const e=document.getElementById(x);if(e)e.value=''})}

// ===== AJUSTES DE PRECIO =====
function vAjustes(){return`<div class="card"><div class="card-header"><h3>Solicitudes de Ajuste</h3><div class="btn-group"><button class="btn btn-primary" onclick="crearAjusteModal()">➕ Nueva</button><button class="btn btn-secondary" onclick="csvAj()">📥 CSV</button></div></div><div class="card-body">
<div class="filters-bar"><select class="form-control" id="faEst" onchange="filtAj()"><option value="">Estado</option>${ESTADOS_AJUSTE.map(e=>`<option>${e}</option>`).join('')}</select><select class="form-control" id="faMot" onchange="filtAj()"><option value="">Motivo</option>${MOTIVOS_AJUSTE.map(m=>`<option>${m}</option>`).join('')}</select></div>
<div class="table-wrap"><table><thead><tr><th>Nº</th><th>SKU</th><th>Motivo</th><th>Acción</th><th>Precio Act.</th><th>Nuevo</th><th>Markup</th><th>Estado</th><th>POS</th><th>Acciones</th></tr></thead><tbody id="tAj">${renderAj(solicitudesAjuste)}</tbody></table></div></div></div>`}
function renderAj(data){return data.map(s=>`<tr><td><strong>${s.numero}</strong></td><td>${s.sku}</td><td>${s.motivo}</td><td>${s.accionSugerida}</td><td>${fmt(s.precioActual)}</td><td><strong>${fmt(s.nuevoPrecio)}</strong></td><td>${calcMarkup(s.nuevoPrecio,s.costo)}%</td><td><span class="badge ${badge(s.estado)}">${s.estado}</span></td><td><span class="badge ${badge(s.posEstado)}">${s.posEstado.substring(0,10)}</span></td><td><div class="btn-group"><button class="btn btn-sm btn-outline" onclick="detAj(${s.id})">👁️</button>${s.estado==='Pendiente de aprobación'?`<button class="btn btn-sm btn-success" onclick="aprobAj(${s.id})">✅</button><button class="btn btn-sm btn-danger" onclick="rechAj(${s.id})">❌</button>`:''} ${s.estado==='Aprobado'?`<button class="btn btn-sm btn-primary" onclick="enviarPOS(${s.id})">🔗</button>`:''}</div></td></tr>`).join('')}
function filtAj(){const e=document.getElementById('faEst').value,m=document.getElementById('faMot').value;let f=solicitudesAjuste.filter(s=>{if(e&&s.estado!==e)return false;if(m&&s.motivo!==m)return false;return true});document.getElementById('tAj').innerHTML=renderAj(f)}
function crearAjuste(id){const p=productos.find(x=>x.id===id);if(!p)return;openModal('Crear Ajuste: '+p.sku,`<div class="form-row"><div class="form-group"><label>Producto</label><input class="form-control" value="${p.sku} - ${p.desc}" readonly></div></div><div class="form-row"><div class="form-group"><label>Precio Actual</label><input class="form-control" value="${fmt(p.precio)}" readonly></div><div class="form-group"><label>Costo</label><input class="form-control" value="${fmt(p.costo)}" readonly></div><div class="form-group"><label>Markup</label><input class="form-control" value="${calcMarkup(p.precio,p.costo)}%" readonly></div></div><div class="form-row"><div class="form-group"><label>Nuevo Precio</label><input type="number" class="form-control" id="aj_np" value="${p.precio}"></div><div class="form-group"><label>Motivo</label><select class="form-control" id="aj_mot">${MOTIVOS_AJUSTE.map(m=>`<option>${m}</option>`).join('')}</select></div></div><div class="form-group"><label>Justificación</label><textarea class="form-control" id="aj_just"></textarea></div>`,`<button class="btn btn-primary" onclick="guardarAj(${p.id})">Crear</button><button class="btn btn-secondary" onclick="closeModal()">Cancelar</button>`)}
function crearAjusteModal(){openModal('Nueva Solicitud',`<div class="form-group"><label>Producto</label><select class="form-control" id="aj_prod">${productos.map(p=>`<option value="${p.id}">${p.sku} - ${p.desc}</option>`).join('')}</select></div><div class="form-row"><div class="form-group"><label>Nuevo Precio</label><input type="number" class="form-control" id="aj_np2"></div><div class="form-group"><label>Motivo</label><select class="form-control" id="aj_mot2">${MOTIVOS_AJUSTE.map(m=>`<option>${m}</option>`).join('')}</select></div></div><div class="form-group"><label>Justificación</label><textarea class="form-control" id="aj_just2"></textarea></div>`,`<button class="btn btn-primary" onclick="guardarAjModal()">Crear</button><button class="btn btn-secondary" onclick="closeModal()">Cancelar</button>`)}
function guardarAj(pid){const p=productos.find(x=>x.id===pid);const np=parseInt(document.getElementById('aj_np').value);const mot=document.getElementById('aj_mot').value;const just=document.getElementById('aj_just').value;const mk=parseFloat(calcMarkup(np,p.costo));let req=false,regla='Cumple reglas';if(Math.abs((np-p.precio)/p.precio*100)>25){req=true;regla='Cambio >25%'}if(mk<reglas.markupPiso){req=true;regla='Markup < piso'}if(parseFloat(calcMargen(np,p.costo))<reglas.margenMin){req=true;regla='Margen < mínimo'}
const sol={id:solicitudesAjuste.length+1,numero:genNumSol(),productoId:pid,sku:p.sku,desc:p.desc,precioActual:p.precio,costo:p.costo,markupActual:parseFloat(calcMarkup(p.precio,p.costo)),precioSugerido:np,nuevoPrecio:np,motivo:mot,accionSugerida:np>p.precio?'Aumentar':'Reducir',justificacion:just,estado:req?'Pendiente de aprobación':'Aplicado',solicitante:'Carlos Mora',fecha:new Date().toISOString().split('T')[0],requiereAprobacion:req,regla,posEstado:req?'Pendiente de envío':'Aplicado en POS'};
solicitudesAjuste.push(sol);if(!req){p.precio=np;p.posEstado='Aplicado en POS';integPOS.aplicados++;simularAPI('POST',p.sku,np)}closeModal();toast(`${sol.numero} ${req?'enviada a aprobación':'aplicada automáticamente'}`);renderView('ajustes')}
function guardarAjModal(){const pid=parseInt(document.getElementById('aj_prod').value);const p=productos.find(x=>x.id===pid);if(!p)return;const np=parseInt(document.getElementById('aj_np2').value);if(!np){toast('Ingrese precio','error');return}const mot=document.getElementById('aj_mot2').value;const just=document.getElementById('aj_just2').value;const mk=parseFloat(calcMarkup(np,p.costo));let req=false,regla='Cumple';if(Math.abs((np-(p.precio||1))/(p.precio||1)*100)>25){req=true;regla='Cambio >25%'}
const sol={id:solicitudesAjuste.length+1,numero:genNumSol(),productoId:pid,sku:p.sku,desc:p.desc,precioActual:p.precio,costo:p.costo,markupActual:parseFloat(calcMarkup(p.precio,p.costo)),precioSugerido:np,nuevoPrecio:np,motivo:mot,accionSugerida:'Ajustar',justificacion:just,estado:req?'Pendiente de aprobación':'Aplicado',solicitante:'Carlos Mora',fecha:new Date().toISOString().split('T')[0],requiereAprobacion:req,regla,posEstado:req?'Pendiente de envío':'Aplicado en POS'};
solicitudesAjuste.push(sol);if(!req){p.precio=np;integPOS.aplicados++}closeModal();toast(`${sol.numero} creada`);renderView('ajustes')}
function detAj(id){const s=solicitudesAjuste.find(x=>x.id===id);if(!s)return;openModal(s.numero,`<div class="product-summary">${[['SKU',s.sku],['Descripción',s.desc],['Precio Actual',fmt(s.precioActual)],['Nuevo Precio',fmt(s.nuevoPrecio)],['Costo',fmt(s.costo)],['Markup Nuevo',calcMarkup(s.nuevoPrecio,s.costo)+'%'],['Motivo',s.motivo],['Acción',s.accionSugerida],['Regla',s.regla],['Solicitante',s.solicitante],['Fecha',s.fecha],['Estado',s.estado],['POS',s.posEstado]].map(([l,v])=>`<div class="product-summary-item"><label>${l}</label><span>${v}</span></div>`).join('')}</div><p class="mt-2"><strong>Justificación:</strong> ${s.justificacion||'-'}</p>`)}
function aprobAj(id){const s=solicitudesAjuste.find(x=>x.id===id);if(s){s.estado='Aprobado';historial.unshift({id:historial.length+1,fecha:new Date().toLocaleString('es-CR'),usuario:'Carlos Mora',sku:s.sku,accion:'Aprobado',precioAnt:s.precioActual,precioNuevo:s.nuevoPrecio,motivo:s.motivo,estado:'Aprobado',fuente:'Aprobaciones',obs:s.numero});toast(s.numero+' aprobada');renderView('ajustes')}}
function rechAj(id){const s=solicitudesAjuste.find(x=>x.id===id);if(s){s.estado='Rechazado';s.posEstado='Rechazado por reglas';toast(s.numero+' rechazada','warning');renderView('ajustes')}}
function enviarPOS(id){const s=solicitudesAjuste.find(x=>x.id===id);if(s){s.posEstado='Aplicado en POS';s.estado='Aplicado';const p=productos.find(x=>x.id===s.productoId);if(p){p.precio=s.nuevoPrecio;p.posEstado='Aplicado en POS'}integPOS.aplicados++;simularAPI('POST',s.sku,s.nuevoPrecio);toast(`${s.sku}: Precio enviado al POS ✅`);renderView('ajustes')}}
function csvAj(){let c='Numero,SKU,Motivo,PrecioActual,NuevoPrecio,Estado,POS\n';solicitudesAjuste.forEach(s=>{c+=`${s.numero},${s.sku},${s.motivo},${s.precioActual},${s.nuevoPrecio},${s.estado},${s.posEstado}\n`});dl(c,'ajustes.csv')}

// ===== APROBACIONES =====
function vAprobaciones(){const pend=solicitudesAjuste.filter(s=>s.estado==='Pendiente de aprobación');return`<div class="kpi-grid" style="grid-template-columns:repeat(3,1fr)"><div class="kpi-card yellow"><div class="kpi-value">${pend.length}</div><div class="kpi-label">Pendientes</div></div><div class="kpi-card green"><div class="kpi-value">${solicitudesAjuste.filter(s=>s.estado==='Aprobado'||s.estado==='Aplicado').length}</div><div class="kpi-label">Aprobadas</div></div><div class="kpi-card red"><div class="kpi-value">${solicitudesAjuste.filter(s=>s.estado==='Rechazado').length}</div><div class="kpi-label">Rechazadas</div></div></div>
<div class="card"><div class="card-header"><h3>Bandeja de Aprobaciones</h3></div><div class="card-body">
${pend.length===0?'<p class="text-center text-muted">Sin solicitudes pendientes</p>':`<div class="table-wrap"><table><thead><tr><th>Nº</th><th>SKU</th><th>Motivo</th><th>Acción</th><th>Precio Act.</th><th>Propuesto</th><th>Dif.</th><th>Markup</th><th>Regla</th><th>Solicitante</th><th>Acciones</th></tr></thead><tbody>
${pend.map(s=>{const diff=s.precioActual?((s.nuevoPrecio-s.precioActual)/s.precioActual*100).toFixed(1):'N/A';return`<tr><td><strong>${s.numero}</strong></td><td>${s.sku}</td><td>${s.motivo}</td><td>${s.accionSugerida}</td><td>${fmt(s.precioActual)}</td><td><strong>${fmt(s.nuevoPrecio)}</strong></td><td class="${parseFloat(diff)<0?'text-danger':'text-success'}">${diff}%</td><td>${calcMarkup(s.nuevoPrecio,s.costo)}%</td><td><small class="text-warning">${s.regla}</small></td><td>${s.solicitante}</td><td><div class="btn-group"><button class="btn btn-sm btn-outline" onclick="detAj(${s.id})">👁️</button><button class="btn btn-sm btn-success" onclick="aprobAj(${s.id});renderView('aprobaciones')">✅</button><button class="btn btn-sm btn-danger" onclick="rechAj(${s.id});renderView('aprobaciones')">❌</button></div></td></tr>`}).join('')}
</tbody></table></div>`}</div></div>`}

// ===== INTEGRACIÓN POS =====
function simularAPI(method,sku,precio){console.log(`[API POS] ${method} /api/pos/precios/actualizar {sku:"${sku}",precio:${precio}}`);return{status:200,message:'OK',timestamp:new Date().toISOString()}}
function vIntegracion(){return`<div class="card"><div class="card-header"><h3>🔗 Estado de Integración - Punto de Venta</h3></div><div class="card-body">
<div class="summary-grid">
<div><div class="api-status"><div class="dot ${integPOS.connected?'green':'red'}"></div><strong>Conexión:</strong> ${integPOS.connected?'Conectado':'Desconectado'}</div>
<div class="api-status"><div class="dot green"></div><strong>Última sync:</strong> ${integPOS.ultimaSync}</div>
<div class="api-status"><div class="dot green"></div><strong>Última consulta:</strong> ${integPOS.ultimaConsulta}</div>
<div class="api-status"><div class="dot green"></div><strong>Último envío:</strong> ${integPOS.ultimoEnvio}</div></div>
<div><div class="kpi-grid" style="grid-template-columns:repeat(2,1fr)">
<div class="kpi-card green"><div class="kpi-value">${integPOS.aplicados}</div><div class="kpi-label">Aplicados</div></div>
<div class="kpi-card yellow"><div class="kpi-value">${integPOS.pendientes}</div><div class="kpi-label">Pendientes</div></div>
<div class="kpi-card red"><div class="kpi-value">${integPOS.errores}</div><div class="kpi-label">Errores</div></div>
<div class="kpi-card purple"><div class="kpi-value">${integPOS.rechazados}</div><div class="kpi-label">Rechazados</div></div>
</div></div></div>
<div class="btn-group mt-3">
<button class="btn btn-primary" onclick="simConsulta()">📡 Consultar Productos</button>
<button class="btn btn-success" onclick="simEnvio()">📤 Enviar Aprobados</button>
<button class="btn btn-warning" onclick="simReproc()">🔄 Reprocesar Errores</button>
</div></div></div>
<div class="card mt-2"><div class="card-header"><h3>Endpoints API Simulados</h3></div><div class="card-body">
<div class="table-wrap"><table><thead><tr><th>Método</th><th>Endpoint</th><th>Descripción</th><th>Estado</th></tr></thead><tbody>
<tr><td><span class="badge badge-success">GET</span></td><td>/api/pos/productos</td><td>Listar productos</td><td><span class="badge badge-success">OK</span></td></tr>
<tr><td><span class="badge badge-success">GET</span></td><td>/api/pos/productos/{sku}/precio</td><td>Consultar precio</td><td><span class="badge badge-success">OK</span></td></tr>
<tr><td><span class="badge badge-success">GET</span></td><td>/api/pos/productos/{sku}/variaciones</td><td>Variaciones</td><td><span class="badge badge-success">OK</span></td></tr>
<tr><td><span class="badge badge-primary">POST</span></td><td>/api/pos/precios/actualizar</td><td>Enviar cambio precio</td><td><span class="badge badge-success">OK</span></td></tr>
<tr><td><span class="badge badge-success">GET</span></td><td>/api/pos/precios/{id}/estado</td><td>Estado del cambio</td><td><span class="badge badge-success">OK</span></td></tr>
<tr><td><span class="badge badge-primary">POST</span></td><td>/api/pos/precios/{id}/reprocesar</td><td>Reprocesar error</td><td><span class="badge badge-success">OK</span></td></tr>
</tbody></table></div>
<div class="ia-box mt-2"><h4>📋 Regla de Aplicación Automática</h4><p>Si un cambio cumple todas las reglas, no requiere aprobación, no tiene alertas críticas, el SKU existe, precio >0, markup en rango, margen ≥ mínimo, sin duplicados, sin inconsistencia de lado, no es neteo, no requiere nuevo código y el usuario está autorizado → se envía automáticamente al POS.</p></div>
</div></div>
<div class="card mt-2"><div class="card-header"><h3>Log de Transacciones</h3></div><div class="card-body"><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>SKU</th><th>Acción</th><th>Estado</th></tr></thead><tbody>
${solicitudesAjuste.filter(s=>s.posEstado!=='Pendiente de envío').slice(0,8).map(s=>`<tr><td>${s.fecha}</td><td>${s.sku}</td><td>${s.accionSugerida} → ${fmt(s.nuevoPrecio)}</td><td><span class="badge ${badge(s.posEstado)}">${s.posEstado}</span></td></tr>`).join('')}
</tbody></table></div></div></div>`}
function simConsulta(){toast(`GET /api/pos/productos → ${productos.length} productos consultados`);integPOS.ultimaConsulta=new Date().toLocaleString('es-CR')}
function simEnvio(){const aprob=solicitudesAjuste.filter(s=>s.estado==='Aprobado');aprob.forEach(s=>{s.posEstado='Aplicado en POS';s.estado='Aplicado';const p=productos.find(x=>x.id===s.productoId);if(p){p.precio=s.nuevoPrecio;p.posEstado='Aplicado en POS'}integPOS.aplicados++});integPOS.ultimoEnvio=new Date().toLocaleString('es-CR');toast(`${aprob.length} cambios enviados al POS`);renderView('integracion')}
function simReproc(){integPOS.errores=0;toast('Errores reprocesados correctamente')}

// ===== HISTÓRICO Y TENDENCIA =====
function vHistorial(){return`<div class="card"><div class="card-header"><h3>Consultar Histórico del Producto</h3></div><div class="card-body">
<div class="form-row"><div class="form-group"><label>Seleccionar Producto</label><select class="form-control" id="hp_prod" onchange="mostrarHist()"><option value="">Seleccionar...</option>${productos.map(p=>`<option value="${p.id}">${p.sku} - ${p.desc} (${p.condicion})</option>`).join('')}</select></div><div class="form-group"><label>Período</label><select class="form-control" id="hp_per"><option>6 meses</option><option>3 meses</option><option>12 meses</option></select></div></div>
</div></div><div id="hp_contenido"></div>`}
function mostrarHist(){const id=parseInt(document.getElementById('hp_prod').value);if(!id){document.getElementById('hp_contenido').innerHTML='';return}
const p=productos.find(x=>x.id===id);const hist=historicoProd[id]||[];const comps=preciosCompetencia.filter(c=>c.productoId===id);
const alertas=[];
if(hist.length>=2){const f=hist[0],l=hist[hist.length-1];if(l.costo>f.costo*1.15&&l.precio<=f.precio*1.05)alertas.push({tipo:'Costo creciente',desc:`Costo +${calcDiff(l.costo,f.costo)}% sin ajuste de precio.`,sev:'Alta'});if(l.margen<f.margen*0.85)alertas.push({tipo:'Margen deteriorado',desc:`Margen bajó de ${f.margen}% a ${l.margen}%.`,sev:'Alta'})}
if(comps.length&&p.precio){const prom=comps.reduce((a,b)=>a+b.promMercado,0)/comps.length;const d=parseFloat(calcDiff(p.precio,prom));if(d>reglas.sobreprecio)alertas.push({tipo:'Sobreprecio',desc:`${d.toFixed(1)}% sobre promedio mercado.`,sev:'Alta'});if(d<-reglas.precioBajo)alertas.push({tipo:'Precio bajo',desc:`${Math.abs(d).toFixed(1)}% debajo mercado. Oportunidad.`,sev:'Media'})}
if(!p.ultimaEval||daysSince(p.ultimaEval)>reglas.diasSinEval)alertas.push({tipo:'Sin evaluación',desc:`>60 días sin evaluación competencia.`,sev:'Media'});

document.getElementById('hp_contenido').innerHTML=`
<div class="card mt-2"><div class="card-header"><h3>Resumen: ${p.sku}</h3></div><div class="card-body"><div class="product-summary">
${[['SKU',p.sku],['Descripción',p.desc],['Condición',p.condicion],['Ingreso',p.tipoIngreso],['Costo',fmt(p.costo)],['Precio',fmt(p.precio)],['Markup',calcMarkup(p.precio,p.costo)+'%'],['Margen',calcMargen(p.precio,p.costo)+'%'],['Inventario',p.inventario],['Rotación',p.rotacion],['Proveedor',p.provActual],['Últ. Eval.',p.ultimaEval||'Nunca'],['Estado',p.estado]].map(([l,v])=>`<div class="product-summary-item"><label>${l}</label><span>${v}</span></div>`).join('')}
</div></div></div>
${alertas.length?`<div class="card mt-2"><div class="card-header"><h3>🚨 Alertas Inteligentes</h3></div><div class="card-body">${alertas.map(a=>`<div style="padding:8px 12px;border-left:4px solid ${a.sev==='Alta'?'var(--danger)':'var(--warning)'};background:${a.sev==='Alta'?'var(--danger-light)':'var(--warning-light)'};border-radius:var(--radius);margin-bottom:6px"><strong>${a.tipo}:</strong> ${a.desc}</div>`).join('')}</div></div>`:''}
<div class="summary-grid mt-2">
<div class="card"><div class="card-header"><h3>📈 Tendencia Precio</h3></div><div class="card-body">${miniChart(hist.map(h=>h.precio),'#1a56db')}</div></div>
<div class="card"><div class="card-header"><h3>💰 Tendencia Costo</h3></div><div class="card-body">${miniChart(hist.map(h=>h.costo),'#dc2626')}</div></div>
<div class="card"><div class="card-header"><h3>📊 Margen %</h3></div><div class="card-body">${miniChart(hist.map(h=>h.margen),'#059669')}</div></div>
<div class="card"><div class="card-header"><h3>🏪 vs Competencia</h3></div><div class="card-body">${comps.length?`<table><thead><tr><th>Competidor</th><th>Precio</th><th>Dif.</th></tr></thead><tbody>${comps.map(c=>`<tr><td>${c.competidor}</td><td>${fmt(c.precio)}</td><td class="${parseFloat(calcDiff(p.precio||1,c.precio))>0?'text-danger':'text-success'}">${calcDiff(p.precio||1,c.precio)}%</td></tr>`).join('')}</tbody></table>`:'<p class="text-muted">Sin datos</p>'}</div></div>
</div>
${hist.length?`<div class="card mt-2"><div class="card-header"><h3>Tabla Histórica</h3></div><div class="card-body"><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Costo</th><th>Precio</th><th>Markup</th><th>Margen</th><th>Prom. Merc.</th><th>Dif. %</th><th>Regla</th><th>Usuario</th><th>Fuente</th></tr></thead><tbody>${hist.map(h=>`<tr><td>${h.fecha}</td><td>${fmt(h.costo)}</td><td>${fmt(h.precio)}</td><td>${h.markup}%</td><td>${h.margen}%</td><td>${fmt(h.promMerc)}</td><td class="${h.diff>0?'text-danger':'text-success'}">${h.diff>0?'+':''}${h.diff}%</td><td>${h.regla}</td><td>${h.usuario}</td><td>${h.fuente}</td></tr>`).join('')}</tbody></table></div></div></div>`:''}`}
function daysSince(d){if(!d)return 999;return Math.floor((new Date()-new Date(d))/86400000)}
function miniChart(vals,color){if(!vals||!vals.length)return'<p class="text-muted text-center">Sin datos</p>';const max=Math.max(...vals),min=Math.min(...vals),range=max-min||1;return`<div class="chart-container"><div class="chart-bars">${vals.map(v=>{const h=((v-min)/range*130)+15;return`<div class="chart-bar" style="height:${h}px;background:${color}"><div class="tip">${v>999?fmt(v):v+'%'}</div></div>`}).join('')}</div></div>`}

// ===== REGLAS Y PARÁMETROS =====
function vReglas(){return`<div class="card"><div class="card-header"><h3>Configuración de Reglas y Parámetros</h3><button class="btn btn-primary" onclick="toast('Reglas guardadas')">💾 Guardar</button></div><div class="card-body">
<div class="rule-card"><h4>🆕 Producto Código Nuevo</h4><p>Variables ponderadas: marca, familia/serie, antigüedad, copro, rotación, origen, rango calidad, precio competencia, marcas competidoras, histórico consumo, disponibilidad origen. <strong>Siempre requiere aprobación.</strong></p></div>
<div class="rule-card"><h4>♻️ Producto Usado Código Nuevo</h4><p>Calidad (A/B/C), disponibilidad, histórico consumo, equivalente nuevo, competencia usado. Precio tope 70% del nuevo. <strong>Siempre requiere aprobación.</strong></p></div>
<div class="rule-card"><h4>📈 Cambio de Costo</h4><p>Variación costo y acción:</p>
<div class="rule-param"><span>< </span><input type="number" value="${reglas.cambioCostoIgnorar}" onchange="reglas.cambioCostoIgnorar=+this.value"><span>% → No cambiar</span></div>
<div class="rule-param"><span>5-</span><input type="number" value="${reglas.cambioCostoRevisar}" onchange="reglas.cambioCostoRevisar=+this.value"><span>% → Revisar</span></div>
<div class="rule-param"><span>> </span><input type="number" value="${reglas.cambioCostoAjustar}" onchange="reglas.cambioCostoAjustar=+this.value"><span>% → Ajustar auto</span></div></div>
<div class="rule-card"><h4>⚠️ Cambio >40% + Proveedor Diferente</h4><p>Crear nuevo código de producto.</p><div class="rule-param"><span>Umbral:</span><input type="number" value="${reglas.cambioProveedor}" onchange="reglas.cambioProveedor=+this.value"><span>%</span></div></div>
<div class="rule-card"><h4>🚫 Neteo de Inventario</h4><p>No aplicar ajuste automático cuando el origen es neteo.</p><span class="badge badge-secondary">Exclusión</span></div>
<div class="rule-card"><h4>🏪 Competencia</h4><p>Alerta sobreprecio cuando excede el permitido sobre mercado.</p><div class="rule-param"><span>Permitido sobre mercado:</span><input type="number" value="${reglas.permitidoSobreMercado}" onchange="reglas.permitidoSobreMercado=+this.value"><span>%</span></div><div class="rule-param"><span>Alerta precio bajo:</span><input type="number" value="${reglas.precioBajo}" onchange="reglas.precioBajo=+this.value"><span>%</span></div></div>
<div class="rule-card"><h4>📊 Markup</h4><p>Excluir markups fuera de rango del cálculo automático.</p><div class="rule-param"><span>Piso:</span><input type="number" value="${reglas.markupPiso}" onchange="reglas.markupPiso=+this.value"><span>%</span></div><div class="rule-param"><span>Techo:</span><input type="number" value="${reglas.markupTecho}" onchange="reglas.markupTecho=+this.value"><span>%</span></div></div>
<div class="rule-card"><h4>📋 Margen Mínimo</h4><div class="rule-param"><span>Mínimo:</span><input type="number" value="${reglas.margenMin}" onchange="reglas.margenMin=+this.value"><span>%</span></div></div>
<div class="rule-card"><h4>↔️ Precio por Lado</h4><p>Izquierdo/derecho = mismo precio. Precio homologado = promedio sugeridos.</p><span class="badge badge-warning">Obligatorio</span></div>
<div class="rule-card"><h4>🏷️ Liquidación</h4><p>Sobre stock + baja rotación → liquidar. Precio = costo + margen mínimo.</p></div>
<div class="rule-card"><h4>⚡ Aplicación Automática</h4><p>Si cumple todas las validaciones: producto existe, SKU activo, precio >0, dentro piso/techo, markup en rango, margen OK, sin aprobación pendiente, sin alerta crítica, sin inconsistencia lado, no neteo, no nuevo código, usuario autorizado.</p><div class="rule-param"><span>Habilitado:</span><input type="checkbox" ${reglas.aplicacionAuto?'checked':''} onchange="reglas.aplicacionAuto=this.checked"></div></div>
<div class="rule-card"><h4>⏰ Sin Evaluación Reciente</h4><div class="rule-param"><span>Días:</span><input type="number" value="${reglas.diasSinEval}" onchange="reglas.diasSinEval=+this.value"><span>días</span></div></div>
</div></div>`}

// ===== LAGO DE DATOS =====
function vLago(){return`<div class="card"><div class="card-header"><h3>Arquitectura del Lago de Datos</h3></div><div class="card-body">
<p style="font-size:13px;line-height:1.7;background:var(--primary-light);padding:14px;border-radius:var(--radius);border-left:4px solid var(--primary);margin-bottom:16px">
<strong>El Lago de Datos</strong> centraliza la información comercial, costos, inventario, histórico de precios, rotación, competencia, productos nuevos/usados y reglas de negocio para alimentar la plataforma de pricing con datos consistentes, trazables y reutilizables.</p>
<div class="arch-diagram">
<div class="arch-layer"><span class="arch-layer-title">Fuentes de Datos</span><div class="arch-items"><div class="arch-item">🏢 POS</div><div class="arch-item">📦 Inventario</div><div class="arch-item">💰 Costos</div><div class="arch-item">🏷️ Maestro</div><div class="arch-item">📈 Ventas</div><div class="arch-item">🏪 Competencia</div><div class="arch-item">📋 Cargas Manuales</div></div></div>
<div class="arch-arrow">⬇️ ⬇️ ⬇️</div>
<div class="arch-layer"><span class="arch-layer-title">Lago de Datos</span><div class="arch-items"><div class="arch-item">📊 Datos Crudos</div><div class="arch-item">🔄 ETL</div><div class="arch-item">📁 Procesados</div><div class="arch-item">🗂️ Históricos</div><div class="arch-item">📐 Modelos</div></div></div>
<div class="arch-arrow">⬇️ ⬇️ ⬇️</div>
<div class="arch-layer"><span class="arch-layer-title">Motor de Inteligencia</span><div class="arch-items"><div class="arch-item">⚙️ Motor Reglas</div><div class="arch-item">🤖 Sugerencias IA</div><div class="arch-item">🧮 Cálculo Pricing</div><div class="arch-item">🔔 Alertas</div><div class="arch-item">✅ Aprobaciones</div></div></div>
<div class="arch-arrow">⬇️ ⬇️ ⬇️</div>
<div class="arch-layer"><span class="arch-layer-title">Plataforma Web</span><div class="arch-items"><div class="arch-item">🏠 Dashboard</div><div class="arch-item">📦 Productos</div><div class="arch-item">🆕 Código Nuevo</div><div class="arch-item">♻️ Usados</div><div class="arch-item">📈 Cambio Costo</div><div class="arch-item">↔️ Homologación</div><div class="arch-item">📡 Competencia</div><div class="arch-item">💰 Ajustes</div></div></div>
<div class="arch-arrow">⬇️ ⬇️ ⬇️</div>
<div class="arch-layer"><span class="arch-layer-title">Integración</span><div class="arch-items"><div class="arch-item">🔗 API REST</div><div class="arch-item">🏪 Punto de Venta</div><div class="arch-item">📊 BI</div><div class="arch-item">📜 Auditoría</div><div class="arch-item">📱 Notificaciones</div></div></div>
</div></div></div>
<div class="summary-grid mt-2">
<div class="card"><div class="card-header"><h3>Flujo Completo</h3></div><div class="card-body"><ol style="font-size:12px;padding-left:16px;line-height:2">
<li>Datos ingresan de fuentes (POS, costos, competencia)</li>
<li>Lago de Datos centraliza y procesa</li>
<li>Motor de reglas evalúa y detecta cambios</li>
<li>IA sugiere precios con explicación</li>
<li>Si cumple reglas → aplicación automática vía API</li>
<li>Si no cumple → envío a aprobación</li>
<li>Aprobado → envío API al POS</li>
<li>Historial y trazabilidad completa</li>
</ol></div></div>
<div class="card"><div class="card-header"><h3>Capacidades IA</h3></div><div class="card-body"><ul style="font-size:12px;padding-left:16px;line-height:2">
<li>Cálculo precio producto nuevo ponderado</li>
<li>Cálculo precio usado con equivalencias</li>
<li>Detección automática de cambios de costo</li>
<li>Homologación inteligente por lado</li>
<li>Monitoreo y matching de competencia</li>
<li>Alertas predictivas de margen</li>
<li>Explicaciones transparentes de cada sugerencia</li>
<li>Aplicación automática con validaciones</li>
</ul></div></div></div>`}
