// ===== PRICING CONTROL HUB V3 - DATOS SIMULADOS =====
const COMPETIDORES=['RAPCO','Repuestos Conejo','Uno Partes','Terrapartes','Auto Sasa','Otros'];
const FUENTES=['Web','Cotización','Llamada','Visita','Archivo','Proveedor','Otro'];
const MOTIVOS_AJUSTE=['Cambio de costo','Competencia','Liquidación','Sobre stock','Bajo stock','Política comercial'];
const ESTADOS_AJUSTE=['Borrador','Pendiente de aprobación','Aprobado','Rechazado','Aplicado','Error'];
const MARCAS=['Toyota','Hyundai','Nissan','Suzuki','Mitsubishi','KIA','Honda','Chevrolet','Mazda','Ford'];
const FAMILIAS=['Suspensión','Frenos','Motor','Eléctrico','Carrocería','Transmisión','Filtros','Encendido','Dirección','Refrigeración'];
const CATEGORIAS=['Original','Alterno','Genérico','Premium','Liquidación'];
const CONDICIONES=['Nuevo','Usado'];
const RANGOS_CALIDAD=['Premium','Medio','Entrada','Usado A','Usado B','Usado C'];
const ORIGENES=['Local','Importado'];
const ESTADOS_POS=['Pendiente de envío','Enviado','Aplicado en POS','Error de integración','Rechazado por reglas','Reprocesado','Sincronizado'];

let productos=[
{id:1,sku:'LG-SUS-001',desc:'Amortiguador Del. Toyota Corolla 14-19',marca:'Toyota',familia:'Suspensión',categoria:'Original',copro:'KYB',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Premium',provActual:'Toyota CR',provAnterior:'Toyota CR',costo:28500,precio:52000,inventario:15,rotacion:'Alta',estado:'Activo',tieneLado:true,lado:'Derecho',skuPareja:'LG-SUS-002',oem:'48510-02490',modelo:'Corolla',ultimaEval:'2024-11-10',alerta:null,posEstado:'Sincronizado'},
{id:2,sku:'LG-SUS-002',desc:'Amortiguador Del. Toyota Corolla 14-19',marca:'Toyota',familia:'Suspensión',categoria:'Original',copro:'KYB',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Premium',provActual:'Toyota CR',provAnterior:'Toyota CR',costo:29200,precio:52000,inventario:12,rotacion:'Alta',estado:'Activo',tieneLado:true,lado:'Izquierdo',skuPareja:'LG-SUS-001',oem:'48520-02490',modelo:'Corolla',ultimaEval:'2024-11-10',alerta:null,posEstado:'Sincronizado'},
{id:3,sku:'LG-FRE-003',desc:'Pastillas Freno Del. Hyundai Tucson 16-20',marca:'Hyundai',familia:'Frenos',categoria:'Original',copro:'Brembo',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Premium',provActual:'Hyundai Mobis',provAnterior:'Hyundai Mobis',costo:12800,precio:32500,inventario:25,rotacion:'Alta',estado:'Sobreprecio',tieneLado:false,lado:'N/A',skuPareja:null,oem:'58101-D3A00',modelo:'Tucson',ultimaEval:'2024-11-14',alerta:'Sobreprecio',posEstado:'Sincronizado'},
{id:4,sku:'LG-MOT-004',desc:'Bomba de Agua Nissan Sentra 13-18',marca:'Nissan',familia:'Motor',categoria:'Alterno',copro:'GMB',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Medio',provActual:'China Parts',provAnterior:'Asia Motors',costo:15200,precio:19500,inventario:8,rotacion:'Media',estado:'Precio bajo',tieneLado:false,lado:'N/A',skuPareja:null,oem:'21010-JA10A',modelo:'Sentra',ultimaEval:'2024-11-05',alerta:'Precio bajo',posEstado:'Sincronizado'},
{id:5,sku:'LG-ELE-005',desc:'Alternador Suzuki Vitara 15-20',marca:'Suzuki',familia:'Eléctrico',categoria:'Premium',copro:'Denso',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Premium',provActual:'Suzuki JP',provAnterior:'Suzuki JP',costo:85000,precio:145000,inventario:3,rotacion:'Baja',estado:'Activo',tieneLado:false,lado:'N/A',skuPareja:null,oem:'31400-54P00',modelo:'Vitara',ultimaEval:'2024-10-20',alerta:null,posEstado:'Sincronizado'},
{id:6,sku:'LG-CAR-006',desc:'Espejo Eléctrico Mitsubishi L200 15-19',marca:'Mitsubishi',familia:'Carrocería',categoria:'Original',copro:'Depo',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Medio',provActual:'Taiwan Auto',provAnterior:'Taiwan Auto',costo:42000,precio:78000,inventario:5,rotacion:'Media',estado:'Sobreprecio',tieneLado:true,lado:'Derecho',skuPareja:'LG-CAR-007',oem:'7632B916',modelo:'L200',ultimaEval:'2024-11-13',alerta:'Sobreprecio',posEstado:'Sincronizado'},
{id:7,sku:'LG-CAR-007',desc:'Espejo Eléctrico Mitsubishi L200 15-19',marca:'Mitsubishi',familia:'Carrocería',categoria:'Original',copro:'Depo',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Medio',provActual:'Taiwan Auto',provAnterior:'Taiwan Auto',costo:44500,precio:78000,inventario:4,rotacion:'Media',estado:'Activo',tieneLado:true,lado:'Izquierdo',skuPareja:'LG-CAR-006',oem:'7632B915',modelo:'L200',ultimaEval:'2024-11-13',alerta:null,posEstado:'Sincronizado'},
{id:8,sku:'LG-FIL-008',desc:'Filtro Aceite KIA Sportage 17-21',marca:'KIA',familia:'Filtros',categoria:'Original',copro:'Mann',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Medio',provActual:'KIA Motors CR',provAnterior:'KIA Motors CR',costo:3200,precio:7800,inventario:50,rotacion:'Alta',estado:'Activo',tieneLado:false,lado:'N/A',skuPareja:null,oem:'26300-35504',modelo:'Sportage',ultimaEval:'2024-11-01',alerta:null,posEstado:'Sincronizado'},
{id:9,sku:'LG-TRA-009',desc:'Kit Clutch Honda CRV 12-16',marca:'Honda',familia:'Transmisión',categoria:'Premium',copro:'Exedy',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Premium',provActual:'Honda JP',provAnterior:'Honda JP',costo:125000,precio:195000,inventario:2,rotacion:'Baja',estado:'Activo',tieneLado:false,lado:'N/A',skuPareja:null,oem:'22300-RX0-003',modelo:'CRV',ultimaEval:'2024-10-05',alerta:'Sin evaluación',posEstado:'Sincronizado'},
{id:10,sku:'LG-ENC-010',desc:'Bobina Encendido Chevrolet Spark 13-17',marca:'Chevrolet',familia:'Encendido',categoria:'Genérico',copro:'NGK',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Entrada',provActual:'China Ignition',provAnterior:'China Ignition',costo:8500,precio:9200,inventario:35,rotacion:'Media',estado:'Margen bajo',tieneLado:false,lado:'N/A',skuPareja:null,oem:'25186686',modelo:'Spark',ultimaEval:'2024-11-10',alerta:'Margen bajo',posEstado:'Sincronizado'},
{id:11,sku:'LG-SUS-011',desc:'Rótula Inf. Toyota Hilux 16-20',marca:'Toyota',familia:'Suspensión',categoria:'Alterno',copro:'555',tipoIngreso:'Código nuevo',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Medio',provActual:'India Auto',provAnterior:null,costo:9800,precio:0,inventario:18,rotacion:'Alta',estado:'Pendiente precio',tieneLado:true,lado:'Derecho',skuPareja:'LG-SUS-012',oem:'43330-09510',modelo:'Hilux',ultimaEval:null,alerta:'Código nuevo',posEstado:'Pendiente de envío'},
{id:12,sku:'LG-SUS-012',desc:'Rótula Inf. Toyota Hilux 16-20',marca:'Toyota',familia:'Suspensión',categoria:'Alterno',copro:'555',tipoIngreso:'Código nuevo',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Medio',provActual:'India Auto',provAnterior:null,costo:10200,precio:0,inventario:16,rotacion:'Alta',estado:'Pendiente precio',tieneLado:true,lado:'Izquierdo',skuPareja:'LG-SUS-011',oem:'43340-09200',modelo:'Hilux',ultimaEval:null,alerta:'Código nuevo',posEstado:'Pendiente de envío'},
{id:13,sku:'LG-FRE-013',desc:'Disco Freno Nissan Frontier 10-15',marca:'Nissan',familia:'Frenos',categoria:'Genérico',copro:'N/A',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Entrada',provActual:'China Brake',provAnterior:'China Brake',costo:18500,precio:22000,inventario:45,rotacion:'Baja',estado:'Liquidación',tieneLado:false,lado:'N/A',skuPareja:null,oem:'40206-EB70A',modelo:'Frontier',ultimaEval:'2024-11-12',alerta:'Sobre stock',posEstado:'Sincronizado'},
{id:14,sku:'LG-MOT-014',desc:'Termostato Hyundai Santa Fe 13-18',marca:'Hyundai',familia:'Motor',categoria:'Original',copro:'Gates',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Medio',provActual:'Hyundai Mobis',provAnterior:'Korea Parts',costo:7200,precio:15800,inventario:10,rotacion:'Media',estado:'Cambio costo',tieneLado:false,lado:'N/A',skuPareja:null,oem:'25500-2G500',modelo:'Santa Fe',ultimaEval:'2024-11-14',alerta:'Cambio costo',posEstado:'Pendiente de envío'},
{id:15,sku:'LG-ELE-015',desc:'Motor Arranque KIA Sorento 15-19',marca:'KIA',familia:'Eléctrico',categoria:'Premium',copro:'Valeo',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Premium',provActual:'KIA Motors',provAnterior:'KIA Motors',costo:95000,precio:168000,inventario:1,rotacion:'Baja',estado:'Sobreprecio',tieneLado:false,lado:'N/A',skuPareja:null,oem:'36100-2F100',modelo:'Sorento',ultimaEval:'2024-11-08',alerta:'Sobreprecio',posEstado:'Sincronizado'},
{id:16,sku:'LG-DIR-016U',desc:'Cremallera Dirección Mazda 3 14-18 (U)',marca:'Mazda',familia:'Dirección',categoria:'Alterno',copro:'N/A',tipoIngreso:'Código nuevo',condicion:'Usado',origen:'Local',rangoCalidad:'Usado A',provActual:'Desarmadero CR',provAnterior:null,costo:65000,precio:0,inventario:2,rotacion:'Baja',estado:'Pendiente precio',tieneLado:false,lado:'N/A',skuPareja:null,oem:'GHT1-32-110',modelo:'Mazda 3',ultimaEval:null,alerta:'Usado nuevo',posEstado:'Pendiente de envío'},
{id:17,sku:'LG-MOT-017U',desc:'Compresor AC Ford Explorer 13-17 (U)',marca:'Ford',familia:'Refrigeración',categoria:'Alterno',copro:'Sanden',tipoIngreso:'Código nuevo',condicion:'Usado',origen:'Local',rangoCalidad:'Usado B',provActual:'Import USA Parts',provAnterior:null,costo:45000,precio:0,inventario:1,rotacion:'Baja',estado:'Pendiente precio',tieneLado:false,lado:'N/A',skuPareja:null,oem:'EB5Z-19703-A',modelo:'Explorer',ultimaEval:null,alerta:'Usado nuevo',posEstado:'Pendiente de envío'},
{id:18,sku:'LG-SUS-018',desc:'Brazo Control Ford Escape 13-19',marca:'Ford',familia:'Suspensión',categoria:'Genérico',copro:'Moog',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Medio',provActual:'New China Sup',provAnterior:'Old China Parts',costo:22000,precio:38000,inventario:7,rotacion:'Media',estado:'Cambio costo 40%',tieneLado:true,lado:'Derecho',skuPareja:'LG-SUS-019',oem:'EV6Z-3078-A',modelo:'Escape',ultimaEval:'2024-11-01',alerta:'Nuevo código',posEstado:'Pendiente de envío'},
{id:19,sku:'LG-SUS-019',desc:'Brazo Control Ford Escape 13-19',marca:'Ford',familia:'Suspensión',categoria:'Genérico',copro:'Moog',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Medio',provActual:'New China Sup',provAnterior:'Old China Parts',costo:23500,precio:38000,inventario:6,rotacion:'Media',estado:'Activo',tieneLado:true,lado:'Izquierdo',skuPareja:'LG-SUS-018',oem:'EV6Z-3079-A',modelo:'Escape',ultimaEval:'2024-11-01',alerta:null,posEstado:'Sincronizado'},
{id:20,sku:'LG-REF-020U',desc:'Radiador Mazda CX-5 13-17 (U)',marca:'Mazda',familia:'Refrigeración',categoria:'Genérico',copro:'N/A',tipoIngreso:'Código nuevo',condicion:'Usado',origen:'Local',rangoCalidad:'Usado C',provActual:'Desarmadero CR',provAnterior:null,costo:35000,precio:0,inventario:1,rotacion:'Baja',estado:'Pendiente precio',tieneLado:false,lado:'N/A',skuPareja:null,oem:'PE01-15-200',modelo:'CX-5',ultimaEval:null,alerta:'Usado nuevo',posEstado:'Pendiente de envío'},
{id:21,sku:'LG-FRE-021',desc:'Zapatas Freno Tras. Toyota Hilux 16-20',marca:'Toyota',familia:'Frenos',categoria:'Alterno',copro:'Bosch',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Medio',provActual:'Bosch CR',provAnterior:'Bosch CR',costo:6500,precio:14200,inventario:20,rotacion:'Media',estado:'Activo',tieneLado:false,lado:'N/A',skuPareja:null,oem:'04495-0K120',modelo:'Hilux',ultimaEval:'2024-10-15',alerta:null,posEstado:'Aplicado en POS'},
{id:22,sku:'LG-SUS-022',desc:'Terminal Dirección Hyundai Tucson (lado incompleto)',marca:'Hyundai',familia:'Dirección',categoria:'Alterno',copro:'CTR',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Medio',provActual:'Korea Steering',provAnterior:'Korea Steering',costo:8200,precio:16500,inventario:4,rotacion:'Media',estado:'Lado incompleto',tieneLado:true,lado:'Derecho',skuPareja:null,oem:'56820-2S000',modelo:'Tucson',ultimaEval:'2024-11-01',alerta:'Lado incompleto',posEstado:'Sincronizado'},
{id:23,sku:'LG-MOT-023',desc:'Bomba Aceite Chevrolet Spark (bajo stock)',marca:'Chevrolet',familia:'Motor',categoria:'Genérico',copro:'N/A',tipoIngreso:'Existente',condicion:'Nuevo',origen:'Importado',rangoCalidad:'Entrada',provActual:'China Oil Pump',provAnterior:'China Oil Pump',costo:18000,precio:32000,inventario:1,rotacion:'Baja',estado:'Bajo stock',tieneLado:false,lado:'N/A',skuPareja:null,oem:'25185643',modelo:'Spark',ultimaEval:'2024-10-20',alerta:'Bajo stock',posEstado:'Sincronizado'}
];

let preciosCompetencia=[
{id:1,productoId:3,competidor:'RAPCO',prodComp:'Pastillas Tucson OEM',precio:26500,promMercado:27500,minMercado:25000,maxMercado:29000,confianza:92,condicion:'Nuevo',fecha:'2024-11-15',fuente:'Web'},
{id:2,productoId:3,competidor:'Repuestos Conejo',prodComp:'Pastillas Tucson Del',precio:27800,promMercado:27500,minMercado:25000,maxMercado:29000,confianza:88,condicion:'Nuevo',fecha:'2024-11-14',fuente:'Cotización'},
{id:3,productoId:4,competidor:'Terrapartes',prodComp:'Bomba Agua Sentra',precio:24500,promMercado:24150,minMercado:23000,maxMercado:25500,confianza:85,condicion:'Nuevo',fecha:'2024-11-10',fuente:'Web'},
{id:4,productoId:4,competidor:'Auto Sasa',prodComp:'Bomba Agua Nissan Sentra',precio:23800,promMercado:24150,minMercado:23000,maxMercado:25500,confianza:90,condicion:'Nuevo',fecha:'2024-11-09',fuente:'Visita'},
{id:5,productoId:6,competidor:'RAPCO',prodComp:'Espejo L200 Elect Der',precio:62000,promMercado:63750,minMercado:60000,maxMercado:67000,confianza:87,condicion:'Nuevo',fecha:'2024-11-13',fuente:'Web'},
{id:6,productoId:6,competidor:'Uno Partes',prodComp:'Retrovisor L200',precio:65500,promMercado:63750,minMercado:60000,maxMercado:67000,confianza:82,condicion:'Nuevo',fecha:'2024-11-11',fuente:'Cotización'},
{id:7,productoId:10,competidor:'Repuestos Conejo',prodComp:'Bobina Spark',precio:14500,promMercado:14150,minMercado:13800,maxMercado:15000,confianza:91,condicion:'Nuevo',fecha:'2024-11-14',fuente:'Web'},
{id:8,productoId:10,competidor:'Terrapartes',prodComp:'Bobina Encendido Spark',precio:13800,promMercado:14150,minMercado:13800,maxMercado:15000,confianza:89,condicion:'Nuevo',fecha:'2024-11-12',fuente:'Web'},
{id:9,productoId:15,competidor:'Auto Sasa',prodComp:'Arranque Sorento 2.4',precio:135000,promMercado:138500,minMercado:132000,maxMercado:145000,confianza:78,condicion:'Nuevo',fecha:'2024-11-08',fuente:'Cotización'},
{id:10,productoId:15,competidor:'RAPCO',prodComp:'Motor Arranque Sorento',precio:142000,promMercado:138500,minMercado:132000,maxMercado:145000,confianza:85,condicion:'Nuevo',fecha:'2024-11-07',fuente:'Web'},
{id:11,productoId:1,competidor:'Uno Partes',prodComp:'Amortiguador Corolla Der',precio:48500,promMercado:48500,minMercado:45000,maxMercado:53000,confianza:93,condicion:'Nuevo',fecha:'2024-11-15',fuente:'Web'},
{id:12,productoId:16,competidor:'RAPCO',prodComp:'Cremallera Mazda 3 Usada',precio:95000,promMercado:100000,minMercado:90000,maxMercado:110000,confianza:72,condicion:'Usado',fecha:'2024-11-10',fuente:'Llamada'},
];
let solicitudesAjuste=[
{id:1,numero:'SA-001',productoId:3,sku:'LG-FRE-003',desc:'Pastillas Freno Tucson',precioActual:32500,costo:12800,markupActual:153.9,precioSugerido:28000,nuevoPrecio:27500,motivo:'Competencia',accionSugerida:'Reducir',justificacion:'Sobreprecio vs mercado',estado:'Pendiente de aprobación',solicitante:'María López',fecha:'2024-11-14',requiereAprobacion:true,regla:'Precio >10% sobre mercado',posEstado:'Pendiente de envío'},
{id:2,numero:'SA-002',productoId:14,sku:'LG-MOT-014',desc:'Termostato Santa Fe',precioActual:15800,costo:7200,markupActual:119.4,precioSugerido:17200,nuevoPrecio:17200,motivo:'Cambio de costo',accionSugerida:'Ajustar',justificacion:'Costo subió 10.8%',estado:'Aplicado',solicitante:'Sistema',fecha:'2024-11-12',requiereAprobacion:false,regla:'Variación >10% aplicación auto',posEstado:'Aplicado en POS'},
{id:3,numero:'SA-003',productoId:13,sku:'LG-FRE-013',desc:'Disco Freno Frontier',precioActual:22000,costo:18500,markupActual:18.9,precioSugerido:18700,nuevoPrecio:18700,motivo:'Liquidación',accionSugerida:'Reducir',justificacion:'Sobre stock + baja rotación',estado:'Aplicado',solicitante:'Ana Vargas',fecha:'2024-11-10',requiereAprobacion:false,regla:'Liquidación',posEstado:'Aplicado en POS'},
{id:4,numero:'SA-004',productoId:15,sku:'LG-ELE-015',desc:'Motor Arranque Sorento',precioActual:168000,costo:95000,markupActual:76.8,precioSugerido:150000,nuevoPrecio:150000,motivo:'Competencia',accionSugerida:'Reducir',justificacion:'Sobreprecio >10% vs mercado',estado:'Pendiente de aprobación',solicitante:'María López',fecha:'2024-11-15',requiereAprobacion:true,regla:'Reducción >10%',posEstado:'Pendiente de envío'},
{id:5,numero:'SA-005',productoId:10,sku:'LG-ENC-010',desc:'Bobina Spark',precioActual:9200,costo:8500,markupActual:8.2,precioSugerido:14000,nuevoPrecio:13500,motivo:'Bajo stock',accionSugerida:'Aumentar',justificacion:'Margen muy bajo, oportunidad aumento',estado:'Pendiente de aprobación',solicitante:'Carlos Mora',fecha:'2024-11-15',requiereAprobacion:true,regla:'Aumento >25%',posEstado:'Pendiente de envío'},
{id:6,numero:'SA-006',productoId:18,sku:'LG-SUS-018',desc:'Brazo Control Escape',precioActual:38000,costo:22000,markupActual:72.7,precioSugerido:42000,nuevoPrecio:42000,motivo:'Cambio de costo',accionSugerida:'Crear nuevo código',justificacion:'Cambio >40% con proveedor diferente',estado:'Pendiente de aprobación',solicitante:'Sistema',fecha:'2024-11-16',requiereAprobacion:true,regla:'Cambio >40% + proveedor diferente',posEstado:'Pendiente de envío'},
];
let historial=[
{id:1,fecha:'2024-11-16 09:30',usuario:'Sistema',sku:'LG-SUS-018',accion:'Alerta: Cambio >40% proveedor diferente',precioAnt:38000,precioNuevo:null,motivo:'Cambio costo',estado:'Alerta',fuente:'Motor reglas',obs:'Recomendar nuevo código'},
{id:2,fecha:'2024-11-15 09:30',usuario:'Carlos Mora',sku:'LG-FRE-003',accion:'Solicitud ajuste',precioAnt:32500,precioNuevo:27500,motivo:'Competencia',estado:'Pendiente',fuente:'Monitoreo',obs:'Sobreprecio vs mercado'},
{id:3,fecha:'2024-11-14 14:15',usuario:'Sistema',sku:'LG-MOT-014',accion:'Aplicación automática',precioAnt:15800,precioNuevo:17200,motivo:'Cambio costo',estado:'Aplicado',fuente:'API POS',obs:'Variación 10.8%, cumple reglas'},
{id:4,fecha:'2024-11-12 11:00',usuario:'Ana Vargas',sku:'LG-FRE-013',accion:'Liquidación aplicada',precioAnt:22000,precioNuevo:18700,motivo:'Liquidación',estado:'Aplicado',fuente:'API POS',obs:'Sobre stock + baja rotación'},
{id:5,fecha:'2024-11-11 16:45',usuario:'Sistema',sku:'LG-ELE-015',accion:'Alerta sobreprecio',precioAnt:168000,precioNuevo:null,motivo:'Competencia',estado:'Alerta',fuente:'Motor reglas',obs:'+21% vs mercado'},
{id:6,fecha:'2024-11-10 08:20',usuario:'Sistema',sku:'LG-ENC-010',accion:'Alerta margen bajo',precioAnt:9200,precioNuevo:null,motivo:'Margen',estado:'Alerta',fuente:'Motor reglas',obs:'Markup 8.2%'},
{id:7,fecha:'2024-11-09 10:00',usuario:'Carlos Mora',sku:'LG-SUS-001',accion:'Precio competencia registrado',precioAnt:null,precioNuevo:null,motivo:'Investigación',estado:'Validado',fuente:'Inv. mercado',obs:'Uno Partes ₡48,500'},
];
let registrosInvestigacion=[
{id:1,productoId:3,sku:'LG-FRE-003',competidor:'RAPCO',prodComp:'Pastillas Tucson',marca:'Hyundai',modelo:'Tucson',oem:'58101-D3A00',categoria:'Frenos',condicion:'Nuevo',precio:26500,moneda:'CRC',fecha:'2024-11-15',fuente:'Web',link:'https://rapco.cr',evidencia:'cap_001.png',obs:'Precio con IVI',validacion:'Validado',usuario:'María López'},
{id:2,productoId:4,sku:'LG-MOT-004',competidor:'Terrapartes',prodComp:'Bomba Agua Sentra',marca:'Nissan',modelo:'Sentra',oem:'21010-JA10A',categoria:'Motor',condicion:'Nuevo',precio:24500,moneda:'CRC',fecha:'2024-11-10',fuente:'Cotización',link:'',evidencia:'',obs:'Teléfono',validacion:'Validado',usuario:'Carlos Mora'},
];

let reglas={sobreprecio:10,precioBajo:15,margenMin:15,markupPiso:17,markupTecho:1000,cambioCostoIgnorar:5,cambioCostoRevisar:10,cambioCostoAjustar:10,cambioProveedor:40,techoPrecio:15,pisoPrecio:-10,permitidoSobreMercado:10,aplicacionAuto:true,diasSinEval:60};
let integPOS={connected:true,ultimaSync:'2024-11-16 08:00',ultimaConsulta:'2024-11-16 09:15',ultimoEnvio:'2024-11-14 14:15',aplicados:12,pendientes:4,errores:1,rechazados:2};
let alertasInteligentes=[
{id:1,sku:'LG-ENC-010',tipo:'Margen deteriorado',desc:'Margen descendente 6 meses, costo +21% sin ajuste precio.',severidad:'Crítica',fecha:'2024-11-15',accion:'Ajustar precio'},
{id:2,sku:'LG-FRE-003',tipo:'Sobreprecio',desc:'Precio 18% sobre promedio de mercado.',severidad:'Alta',fecha:'2024-11-15',accion:'Reducir precio'},
{id:3,sku:'LG-MOT-004',tipo:'Precio bajo',desc:'20% por debajo del mercado. Oportunidad de margen.',severidad:'Media',fecha:'2024-11-14',accion:'Aumentar precio'},
{id:4,sku:'LG-SUS-018',tipo:'Cambio costo >40%',desc:'Proveedor diferente, costo +51.7%. Crear nuevo código.',severidad:'Crítica',fecha:'2024-11-16',accion:'Nuevo código'},
{id:5,sku:'LG-TRA-009',tipo:'Sin evaluación',desc:'No se evalúa competencia hace >60 días.',severidad:'Media',fecha:'2024-11-13',accion:'Evaluar competencia'},
{id:6,sku:'LG-REF-020U',tipo:'Usado sin precio',desc:'Producto usado código nuevo sin precio asignado.',severidad:'Alta',fecha:'2024-11-06',accion:'Calcular precio'},
{id:7,sku:'LG-SUS-022',tipo:'Lado incompleto',desc:'Producto con lado sin pareja identificada.',severidad:'Media',fecha:'2024-11-05',accion:'Buscar pareja'},
{id:8,sku:'LG-MOT-023',tipo:'Bajo stock',desc:'Inventario bajo, posible oportunidad de aumento.',severidad:'Baja',fecha:'2024-11-10',accion:'Revisar precio'},
];
let historicoProd={
1:[{fecha:'2024-05',costo:26000,precio:48000,markup:84.6,margen:45.8,promMerc:46000,min:43000,max:50000,comp:3,diff:4.3,regla:'-',accion:'-',usuario:'Sistema',fuente:'ERP',obs:''},{fecha:'2024-07',costo:27500,precio:50000,markup:81.8,margen:45.0,promMerc:47000,min:44000,max:51000,comp:3,diff:6.4,regla:'-',accion:'Ajuste',usuario:'Carlos',fuente:'Manual',obs:'Cambio costo'},{fecha:'2024-10',costo:28500,precio:52000,markup:82.5,margen:45.2,promMerc:48500,min:45000,max:53000,comp:4,diff:7.2,regla:'-',accion:'Ajuste',usuario:'Carlos',fuente:'Manual',obs:''}],
10:[{fecha:'2024-01',costo:7000,precio:12500,markup:78.6,margen:44.0,promMerc:13000,min:11000,max:15000,comp:2,diff:-3.8,regla:'-',accion:'-',usuario:'Sistema',fuente:'ERP',obs:''},{fecha:'2024-04',costo:7500,precio:9200,markup:22.7,margen:18.5,promMerc:13500,min:12000,max:15500,comp:3,diff:-31.9,regla:'Error',accion:'Error precio',usuario:'Sistema',fuente:'ERP',obs:'Precio bajó por error'},{fecha:'2024-08',costo:8200,precio:9200,markup:12.2,margen:10.9,promMerc:14000,min:13000,max:15000,comp:3,diff:-34.3,regla:'Margen bajo',accion:'-',usuario:'Sistema',fuente:'ERP',obs:''},{fecha:'2024-11',costo:8500,precio:9200,markup:8.2,margen:7.6,promMerc:14150,min:13800,max:14500,comp:2,diff:-35.0,regla:'Margen bajo',accion:'Pendiente',usuario:'Sistema',fuente:'Motor',obs:'Tendencia negativa'}]
};
// ===== UTILIDADES =====
function fmt(n){if(!n&&n!==0)return'-';return'₡'+n.toLocaleString('es-CR')}
function pct(v){return v==null?'-':v+'%'}
function calcMargen(p,c){if(!p||p===0)return 0;return((p-c)/p*100).toFixed(1)}
function calcMarkup(p,c){if(!c||c===0)return 0;return((p-c)/c*100).toFixed(1)}
function calcDiff(a,b){if(!b||b===0)return 0;return((a-b)/b*100).toFixed(1)}
function badge(estado){const m={'Activo':'badge-success','Sobreprecio':'badge-danger','Precio bajo':'badge-warning','Pendiente precio':'badge-info','Código nuevo':'badge-info','Cambio costo':'badge-primary','Cambio costo 40%':'badge-danger','Liquidación':'badge-secondary','Margen bajo':'badge-warning','Lado incompleto':'badge-warning','Bajo stock':'badge-purple','Pendiente de aprobación':'badge-warning','Aprobado':'badge-success','Rechazado':'badge-danger','Aplicado':'badge-success','Error':'badge-danger','Pendiente de envío':'badge-warning','Enviado':'badge-info','Aplicado en POS':'badge-success','Error de integración':'badge-danger','Sincronizado':'badge-success','Validado':'badge-success','Pendiente':'badge-warning','Alerta':'badge-danger','Crítica':'badge-danger','Alta':'badge-warning','Media':'badge-info','Baja':'badge-secondary','En rango':'badge-success','Fuera rango':'badge-danger','Nuevo':'badge-info','Usado':'badge-purple'};return m[estado]||'badge-secondary'}
function genNumSol(){return'SA-'+String(solicitudesAjuste.length+1).padStart(3,'0')}
